FROM alpine:3.23

## RUN echo "https://mirrors.aliyun.com/alpine/v3.23/main" > /etc/apk/repositories && \
##   echo "https://mirrors.aliyun.com/alpine/v3.23/community" >> /etc/apk/repositories && \
##   echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/main" >> /etc/apk/repositories && \
##   echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/community" >> /etc/apk/repositories

RUN echo "https://mirrors.aliyun.com/alpine/v3.23/main" > /etc/apk/repositories && \
  echo "https://mirrors.aliyun.com/alpine/v3.23/community" >> /etc/apk/repositories

#RUN apk add --update --no-cache ca-certificates bash openssh openssh-server git gcompat tzdata rsync
#RUN apk add --update --no-cache ca-certificates bash git gcompat tzdata rsync procps
RUN apk add --update --no-cache ca-certificates bash gcompat tzdata rsync procps

RUN adduser -h /home/action -s /bin/sh -u 2048 -D action

## RUN adduser -h /home/action -s /bin/sh -u 2048 -D action && \
##   ssh-keygen -A && \
##   mkdir -p /home/action/.ssh && \
##   mv /etc/ssh/ssh_host_* /home/action/.ssh/ && \ 
##   chown -R action:action /home/action/.ssh && \
##   sed -i 's/#Port 22/Port 2022/g' /etc/ssh/sshd_config && \
##   sed -i 's/#PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config && \
##   sed -i 's/GSSAPIAuthentication.*/GSSAPIAuthentication no/g' /etc/ssh/sshd_config && \
##   sed -i 's/#UseDNS.*/UseDNS no/g' /etc/ssh/sshd_config && \
##   sed -i 's/etc\/ssh\/ssh_host_rsa_key/home\/action\/.ssh\/ssh_host_rsa_key/g' /etc/ssh/sshd_config && \
##   sed -i 's/etc\/ssh\/ssh_host_ecdsa_key/home\/action\/.ssh\/ssh_host_ecdsa_key/g' /etc/ssh/sshd_config && \
##   sed -i 's/etc\/ssh\/ssh_host_ed25519_key/home\/action\/.ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config && \
##   sed -i 's/#HostKey /HostKey /g' /etc/ssh/sshd_config && \
##   chmod 644 /etc/ssh/sshd_config

# EXPOSE 2022

WORKDIR /home/action

ENV USER=action
ENV HOME=/home/action
