// Copyright 2015 Eryx <evorui аt gmаil dοt cοm>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.2
// source: app.proto

package inapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Labels      map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" toml:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" toml:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Operate     *AppOperate       `protobuf:"bytes,90,opt,name=operate,proto3" json:"operate,omitempty" toml:"operate,omitempty"`
	Spec        *AppSpec          `protobuf:"bytes,100,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty"`
}

func (x *AppInstance) Reset() {
	*x = AppInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInstance) ProtoMessage() {}

func (x *AppInstance) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInstance.ProtoReflect.Descriptor instead.
func (*AppInstance) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInstance) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AppInstance) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AppInstance) GetOperate() *AppOperate {
	if x != nil {
		return x.Operate
	}
	return nil
}

func (x *AppInstance) GetSpec() *AppSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type AppReplicaInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	Operate *AppOperate        `protobuf:"bytes,90,opt,name=operate,proto3" json:"operate,omitempty" toml:"operate,omitempty"`
	Replica *AppOperateReplica `protobuf:"bytes,91,opt,name=replica,proto3" json:"replica,omitempty" toml:"replica,omitempty"`
	Spec    *AppSpec           `protobuf:"bytes,100,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty"`
}

func (x *AppReplicaInstance) Reset() {
	*x = AppReplicaInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppReplicaInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReplicaInstance) ProtoMessage() {}

func (x *AppReplicaInstance) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReplicaInstance.ProtoReflect.Descriptor instead.
func (*AppReplicaInstance) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppReplicaInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppReplicaInstance) GetOperate() *AppOperate {
	if x != nil {
		return x.Operate
	}
	return nil
}

func (x *AppReplicaInstance) GetReplica() *AppOperateReplica {
	if x != nil {
		return x.Replica
	}
	return nil
}

func (x *AppReplicaInstance) GetSpec() *AppSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type AppSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Description    string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	RuntimeImage   string           `protobuf:"bytes,5,opt,name=runtime_image,json=runtimeImage,proto3" json:"runtime_image,omitempty" toml:"runtime_image,omitempty"`
	CpuLimit       string           `protobuf:"bytes,10,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty" toml:"cpu_limit,omitempty"`
	MemoryLimit    string           `protobuf:"bytes,11,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty" toml:"memory_limit,omitempty"`
	VolumeLimit    string           `protobuf:"bytes,12,opt,name=volume_limit,json=volumeLimit,proto3" json:"volume_limit,omitempty" toml:"volume_limit,omitempty"`
	ServicePorts   *AppServicePort  `protobuf:"bytes,13,opt,name=service_ports,json=servicePorts,proto3" json:"service_ports,omitempty" toml:"service_ports,omitempty"`
	Executors      []*AppExecutor   `protobuf:"bytes,19,rep,name=executors,proto3" json:"executors,omitempty" toml:"executors,omitempty"`
	Packages       []*AppPackage    `protobuf:"bytes,20,rep,name=packages,proto3" json:"packages,omitempty" toml:"packages,omitempty"`
	Depends        []*AppSpecDepend `protobuf:"bytes,21,rep,name=depends,proto3" json:"depends,omitempty" toml:"depends,omitempty"`
	ServiceDepends []*AppSpecDepend `protobuf:"bytes,22,rep,name=service_depends,json=serviceDepends,proto3" json:"service_depends,omitempty" toml:"service_depends,omitempty"`
}

func (x *AppSpec) Reset() {
	*x = AppSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpec) ProtoMessage() {}

func (x *AppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpec.ProtoReflect.Descriptor instead.
func (*AppSpec) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppSpec) GetRuntimeImage() string {
	if x != nil {
		return x.RuntimeImage
	}
	return ""
}

func (x *AppSpec) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *AppSpec) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *AppSpec) GetVolumeLimit() string {
	if x != nil {
		return x.VolumeLimit
	}
	return ""
}

func (x *AppSpec) GetServicePorts() *AppServicePort {
	if x != nil {
		return x.ServicePorts
	}
	return nil
}

func (x *AppSpec) GetExecutors() []*AppExecutor {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *AppSpec) GetPackages() []*AppPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AppSpec) GetDepends() []*AppSpecDepend {
	if x != nil {
		return x.Depends
	}
	return nil
}

func (x *AppSpec) GetServiceDepends() []*AppSpecDepend {
	if x != nil {
		return x.ServiceDepends
	}
	return nil
}

type AppPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
}

func (x *AppPackage) Reset() {
	*x = AppPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPackage) ProtoMessage() {}

func (x *AppPackage) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPackage.ProtoReflect.Descriptor instead.
func (*AppPackage) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AppSpecDepend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
}

func (x *AppSpecDepend) Reset() {
	*x = AppSpecDepend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecDepend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecDepend) ProtoMessage() {}

func (x *AppSpecDepend) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecDepend.ProtoReflect.Descriptor instead.
func (*AppSpecDepend) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppSpecDepend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecDepend) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AppServicePort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port      uint32               `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty" toml:"port,omitempty"`
	Name      string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Endpoints []*AppServiceReplica `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty" toml:"endpoints,omitempty"`
}

func (x *AppServicePort) Reset() {
	*x = AppServicePort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppServicePort) ProtoMessage() {}

func (x *AppServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppServicePort.ProtoReflect.Descriptor instead.
func (*AppServicePort) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppServicePort) GetEndpoints() []*AppServiceReplica {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type AppServiceReplica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rep     uint32 `protobuf:"varint,1,opt,name=rep,proto3" json:"rep,omitempty" toml:"rep,omitempty"`
	Ip      string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty" toml:"ip,omitempty"`
	Port    uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty" toml:"port,omitempty"`
	VpcIpv4 string `protobuf:"bytes,4,opt,name=vpc_ipv4,json=vpcIpv4,proto3" json:"vpc_ipv4,omitempty" toml:"vpc_ipv4,omitempty"`
}

func (x *AppServiceReplica) Reset() {
	*x = AppServiceReplica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppServiceReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppServiceReplica) ProtoMessage() {}

func (x *AppServiceReplica) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppServiceReplica.ProtoReflect.Descriptor instead.
func (*AppServiceReplica) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppServiceReplica) GetRep() uint32 {
	if x != nil {
		return x.Rep
	}
	return 0
}

func (x *AppServiceReplica) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AppServiceReplica) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppServiceReplica) GetVpcIpv4() string {
	if x != nil {
		return x.VpcIpv4
	}
	return ""
}

type AppExecutor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Updated     int64              `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty" toml:"updated,omitempty"`
	Vendor      string             `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty" toml:"vendor,omitempty"`
	Dir         string             `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty" toml:"dir,omitempty"`
	User        string             `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty" toml:"user,omitempty"`
	Group       string             `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty" toml:"group,omitempty"`
	StartScript string             `protobuf:"bytes,10,opt,name=start_script,json=startScript,proto3" json:"start_script,omitempty" toml:"start_script,omitempty"`
	StopScript  string             `protobuf:"bytes,11,opt,name=stop_script,json=stopScript,proto3" json:"stop_script,omitempty" toml:"stop_script,omitempty"`
	Priority    uint32             `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty" toml:"priority,omitempty"`
	Plan        *AppExecPlanner    `protobuf:"bytes,13,opt,name=plan,proto3" json:"plan,omitempty" toml:"plan,omitempty"`
	Options     []*Label           `protobuf:"bytes,14,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty"`
	Status      *AppExecutorStatus `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty" toml:"status,omitempty"`
}

func (x *AppExecutor) Reset() {
	*x = AppExecutor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExecutor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExecutor) ProtoMessage() {}

func (x *AppExecutor) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExecutor.ProtoReflect.Descriptor instead.
func (*AppExecutor) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{7}
}

func (x *AppExecutor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppExecutor) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *AppExecutor) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AppExecutor) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *AppExecutor) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AppExecutor) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AppExecutor) GetStartScript() string {
	if x != nil {
		return x.StartScript
	}
	return ""
}

func (x *AppExecutor) GetStopScript() string {
	if x != nil {
		return x.StopScript
	}
	return ""
}

func (x *AppExecutor) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AppExecutor) GetPlan() *AppExecPlanner {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *AppExecutor) GetOptions() []*Label {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AppExecutor) GetStatus() *AppExecutorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AppExecPlanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnBoot     bool                 `protobuf:"varint,1,opt,name=on_boot,json=onBoot,proto3" json:"on_boot,omitempty" toml:"on_boot,omitempty"`
	OnTick     uint32               `protobuf:"varint,2,opt,name=on_tick,json=onTick,proto3" json:"on_tick,omitempty" toml:"on_tick,omitempty"`
	OnCalendar string               `protobuf:"bytes,3,opt,name=on_calendar,json=onCalendar,proto3" json:"on_calendar,omitempty" toml:"on_calendar,omitempty"`
	OnFailed   *AppExecPlanOnFailed `protobuf:"bytes,4,opt,name=on_failed,json=onFailed,proto3" json:"on_failed,omitempty" toml:"on_failed,omitempty"`
}

func (x *AppExecPlanner) Reset() {
	*x = AppExecPlanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExecPlanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExecPlanner) ProtoMessage() {}

func (x *AppExecPlanner) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExecPlanner.ProtoReflect.Descriptor instead.
func (*AppExecPlanner) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{8}
}

func (x *AppExecPlanner) GetOnBoot() bool {
	if x != nil {
		return x.OnBoot
	}
	return false
}

func (x *AppExecPlanner) GetOnTick() uint32 {
	if x != nil {
		return x.OnTick
	}
	return 0
}

func (x *AppExecPlanner) GetOnCalendar() string {
	if x != nil {
		return x.OnCalendar
	}
	return ""
}

func (x *AppExecPlanner) GetOnFailed() *AppExecPlanOnFailed {
	if x != nil {
		return x.OnFailed
	}
	return nil
}

type AppExecPlanOnFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetrySec string `protobuf:"bytes,1,opt,name=retry_sec,json=retrySec,proto3" json:"retry_sec,omitempty" toml:"retry_sec,omitempty"`
	RetryMax int32  `protobuf:"varint,2,opt,name=retry_max,json=retryMax,proto3" json:"retry_max,omitempty" toml:"retry_max,omitempty"`
}

func (x *AppExecPlanOnFailed) Reset() {
	*x = AppExecPlanOnFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExecPlanOnFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExecPlanOnFailed) ProtoMessage() {}

func (x *AppExecPlanOnFailed) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExecPlanOnFailed.ProtoReflect.Descriptor instead.
func (*AppExecPlanOnFailed) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{9}
}

func (x *AppExecPlanOnFailed) GetRetrySec() string {
	if x != nil {
		return x.RetrySec
	}
	return ""
}

func (x *AppExecPlanOnFailed) GetRetryMax() int32 {
	if x != nil {
		return x.RetryMax
	}
	return 0
}

type AppExecutorStatusPlanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated          int64 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty" toml:"updated,omitempty"`
	OnFailedRetryNum int32 `protobuf:"varint,2,opt,name=on_failed_retry_num,json=onFailedRetryNum,proto3" json:"on_failed_retry_num,omitempty" toml:"on_failed_retry_num,omitempty"`
}

func (x *AppExecutorStatusPlanner) Reset() {
	*x = AppExecutorStatusPlanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExecutorStatusPlanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExecutorStatusPlanner) ProtoMessage() {}

func (x *AppExecutorStatusPlanner) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExecutorStatusPlanner.ProtoReflect.Descriptor instead.
func (*AppExecutorStatusPlanner) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{10}
}

func (x *AppExecutorStatusPlanner) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *AppExecutorStatusPlanner) GetOnFailedRetryNum() int32 {
	if x != nil {
		return x.OnFailedRetryNum
	}
	return 0
}

type AppExecutorStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Created int64                     `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty" toml:"created,omitempty"`
	Updated int64                     `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty" toml:"updated,omitempty"`
	Vendor  string                    `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty" toml:"vendor,omitempty"`
	Action  uint64                    `protobuf:"varint,5,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	Plan    *AppExecutorStatusPlanner `protobuf:"bytes,6,opt,name=plan,proto3" json:"plan,omitempty" toml:"plan,omitempty"`
}

func (x *AppExecutorStatus) Reset() {
	*x = AppExecutorStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppExecutorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppExecutorStatus) ProtoMessage() {}

func (x *AppExecutorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppExecutorStatus.ProtoReflect.Descriptor instead.
func (*AppExecutorStatus) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{11}
}

func (x *AppExecutorStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppExecutorStatus) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *AppExecutorStatus) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *AppExecutorStatus) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *AppExecutorStatus) GetAction() uint64 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *AppExecutorStatus) GetPlan() *AppExecutorStatusPlanner {
	if x != nil {
		return x.Plan
	}
	return nil
}

type AppOperate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action      string               `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	CpuLimit    int64                `protobuf:"varint,10,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty" toml:"cpu_limit,omitempty"`
	MemoryLimit int64                `protobuf:"varint,11,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty" toml:"memory_limit,omitempty"`
	VolumeLimit int64                `protobuf:"varint,12,opt,name=volume_limit,json=volumeLimit,proto3" json:"volume_limit,omitempty" toml:"volume_limit,omitempty"`
	Options     []*AppOperateOption  `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty"`
	Services    []*AppServicePort    `protobuf:"bytes,14,rep,name=services,proto3" json:"services,omitempty" toml:"services,omitempty"`
	ReplicaCap  uint32               `protobuf:"varint,19,opt,name=replica_cap,json=replicaCap,proto3" json:"replica_cap,omitempty" toml:"replica_cap,omitempty"`
	Replicas    []*AppOperateReplica `protobuf:"bytes,20,rep,name=replicas,proto3" json:"replicas,omitempty" toml:"replicas,omitempty"`
}

func (x *AppOperate) Reset() {
	*x = AppOperate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppOperate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOperate) ProtoMessage() {}

func (x *AppOperate) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOperate.ProtoReflect.Descriptor instead.
func (*AppOperate) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{12}
}

func (x *AppOperate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AppOperate) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *AppOperate) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *AppOperate) GetVolumeLimit() int64 {
	if x != nil {
		return x.VolumeLimit
	}
	return 0
}

func (x *AppOperate) GetOptions() []*AppOperateOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AppOperate) GetServices() []*AppServicePort {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *AppOperate) GetReplicaCap() uint32 {
	if x != nil {
		return x.ReplicaCap
	}
	return 0
}

func (x *AppOperate) GetReplicas() []*AppOperateReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type AppOperateOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Items []*AppOperateOptionField `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
}

func (x *AppOperateOption) Reset() {
	*x = AppOperateOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppOperateOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOperateOption) ProtoMessage() {}

func (x *AppOperateOption) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOperateOption.ProtoReflect.Descriptor instead.
func (*AppOperateOption) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{13}
}

func (x *AppOperateOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppOperateOption) GetItems() []*AppOperateOptionField {
	if x != nil {
		return x.Items
	}
	return nil
}

type AppOperateOptionField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty"`
}

func (x *AppOperateOptionField) Reset() {
	*x = AppOperateOptionField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppOperateOptionField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOperateOptionField) ProtoMessage() {}

func (x *AppOperateOptionField) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOperateOptionField.ProtoReflect.Descriptor instead.
func (*AppOperateOptionField) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{14}
}

func (x *AppOperateOptionField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppOperateOptionField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AppOperateReplica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	HostId string `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty" toml:"host_id,omitempty"`
}

func (x *AppOperateReplica) Reset() {
	*x = AppOperateReplica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppOperateReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOperateReplica) ProtoMessage() {}

func (x *AppOperateReplica) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOperateReplica.ProtoReflect.Descriptor instead.
func (*AppOperateReplica) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{15}
}

func (x *AppOperateReplica) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppOperateReplica) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

var File_app_proto protoreflect.FileDescriptor

var file_app_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x61,
	0x70, 0x69, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xfc, 0x02, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x45, 0x0a, 0x0b,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x5a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x3e, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xa9, 0x01, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x18, 0x5b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x07,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70,
	0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0xd3, 0x03, 0x0a, 0x07,
	0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x70, 0x75, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x73, 0x12, 0x30, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x13,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70,
	0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x15, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53,
	0x70, 0x65, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x07, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a,
	0x0d, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x0e,
	0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x64,
	0x0a, 0x11, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x72, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x70, 0x63,
	0x5f, 0x69, 0x70, 0x76, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x70, 0x63,
	0x49, 0x70, 0x76, 0x34, 0x22, 0xf4, 0x02, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f,
	0x70, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x6f, 0x70, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x45, 0x78, 0x65, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x70, 0x6c, 0x61,
	0x6e, 0x12, 0x26, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x0e,
	0x41, 0x70, 0x70, 0x45, 0x78, 0x65, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x6f, 0x6e, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x6e, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x6e, 0x54, 0x69, 0x63, 0x6b,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61,
	0x72, 0x12, 0x37, 0x0a, 0x09, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70,
	0x45, 0x78, 0x65, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x52, 0x08, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x4f, 0x0a, 0x13, 0x41, 0x70,
	0x70, 0x45, 0x78, 0x65, 0x63, 0x50, 0x6c, 0x61, 0x6e, 0x4f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x74, 0x72, 0x79, 0x53, 0x65, 0x63, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x65, 0x74, 0x72, 0x79, 0x4d, 0x61, 0x78, 0x22, 0x63, 0x0a, 0x18, 0x41,
	0x70, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x2d, 0x0a, 0x13, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x74, 0x72, 0x79, 0x4e, 0x75, 0x6d,
	0x22, 0xc0, 0x01, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33,
	0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x70,
	0x6c, 0x61, 0x6e, 0x22, 0xc4, 0x02, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70,
	0x75, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x70, 0x75, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x31, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x31, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x63,
	0x61, 0x70, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x43, 0x61, 0x70, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73,
	0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x70, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x5a, 0x0a, 0x10, 0x41, 0x70,
	0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x41, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x11, 0x41, 0x70, 0x70,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x69, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData = file_app_proto_rawDesc
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_rawDescData)
	})
	return file_app_proto_rawDescData
}

var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_proto_goTypes = []interface{}{
	(*AppInstance)(nil),              // 0: inapi.AppInstance
	(*AppReplicaInstance)(nil),       // 1: inapi.AppReplicaInstance
	(*AppSpec)(nil),                  // 2: inapi.AppSpec
	(*AppPackage)(nil),               // 3: inapi.AppPackage
	(*AppSpecDepend)(nil),            // 4: inapi.AppSpecDepend
	(*AppServicePort)(nil),           // 5: inapi.AppServicePort
	(*AppServiceReplica)(nil),        // 6: inapi.AppServiceReplica
	(*AppExecutor)(nil),              // 7: inapi.AppExecutor
	(*AppExecPlanner)(nil),           // 8: inapi.AppExecPlanner
	(*AppExecPlanOnFailed)(nil),      // 9: inapi.AppExecPlanOnFailed
	(*AppExecutorStatusPlanner)(nil), // 10: inapi.AppExecutorStatusPlanner
	(*AppExecutorStatus)(nil),        // 11: inapi.AppExecutorStatus
	(*AppOperate)(nil),               // 12: inapi.AppOperate
	(*AppOperateOption)(nil),         // 13: inapi.AppOperateOption
	(*AppOperateOptionField)(nil),    // 14: inapi.AppOperateOptionField
	(*AppOperateReplica)(nil),        // 15: inapi.AppOperateReplica
	nil,                              // 16: inapi.AppInstance.LabelsEntry
	nil,                              // 17: inapi.AppInstance.AnnotationsEntry
	(*Label)(nil),                    // 18: inapi.Label
}
var file_app_proto_depIdxs = []int32{
	16, // 0: inapi.AppInstance.labels:type_name -> inapi.AppInstance.LabelsEntry
	17, // 1: inapi.AppInstance.annotations:type_name -> inapi.AppInstance.AnnotationsEntry
	12, // 2: inapi.AppInstance.operate:type_name -> inapi.AppOperate
	2,  // 3: inapi.AppInstance.spec:type_name -> inapi.AppSpec
	12, // 4: inapi.AppReplicaInstance.operate:type_name -> inapi.AppOperate
	15, // 5: inapi.AppReplicaInstance.replica:type_name -> inapi.AppOperateReplica
	2,  // 6: inapi.AppReplicaInstance.spec:type_name -> inapi.AppSpec
	5,  // 7: inapi.AppSpec.service_ports:type_name -> inapi.AppServicePort
	7,  // 8: inapi.AppSpec.executors:type_name -> inapi.AppExecutor
	3,  // 9: inapi.AppSpec.packages:type_name -> inapi.AppPackage
	4,  // 10: inapi.AppSpec.depends:type_name -> inapi.AppSpecDepend
	4,  // 11: inapi.AppSpec.service_depends:type_name -> inapi.AppSpecDepend
	6,  // 12: inapi.AppServicePort.endpoints:type_name -> inapi.AppServiceReplica
	8,  // 13: inapi.AppExecutor.plan:type_name -> inapi.AppExecPlanner
	18, // 14: inapi.AppExecutor.options:type_name -> inapi.Label
	11, // 15: inapi.AppExecutor.status:type_name -> inapi.AppExecutorStatus
	9,  // 16: inapi.AppExecPlanner.on_failed:type_name -> inapi.AppExecPlanOnFailed
	10, // 17: inapi.AppExecutorStatus.plan:type_name -> inapi.AppExecutorStatusPlanner
	13, // 18: inapi.AppOperate.options:type_name -> inapi.AppOperateOption
	5,  // 19: inapi.AppOperate.services:type_name -> inapi.AppServicePort
	15, // 20: inapi.AppOperate.replicas:type_name -> inapi.AppOperateReplica
	14, // 21: inapi.AppOperateOption.items:type_name -> inapi.AppOperateOptionField
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppReplicaInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecDepend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppServicePort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppServiceReplica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExecutor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExecPlanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExecPlanOnFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExecutorStatusPlanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppExecutorStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppOperate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppOperateOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppOperateOptionField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppOperateReplica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_rawDesc = nil
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
