// Copyright 2015 Eryx <evorui аt gmаil dοt cοm>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: service.proto

package inapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Hostlet_HostInit_FullMethodName = "/inapi.Hostlet/HostInit"
)

// HostletClient is the client API for Hostlet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostletClient interface {
	// HostInit initializes a new host and registers it with the specified zone.
	HostInit(ctx context.Context, in *HostInitRequest, opts ...grpc.CallOption) (*HostInitResponse, error)
}

type hostletClient struct {
	cc grpc.ClientConnInterface
}

func NewHostletClient(cc grpc.ClientConnInterface) HostletClient {
	return &hostletClient{cc}
}

func (c *hostletClient) HostInit(ctx context.Context, in *HostInitRequest, opts ...grpc.CallOption) (*HostInitResponse, error) {
	out := new(HostInitResponse)
	err := c.cc.Invoke(ctx, Hostlet_HostInit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostletServer is the server API for Hostlet service.
// All implementations must embed UnimplementedHostletServer
// for forward compatibility
type HostletServer interface {
	// HostInit initializes a new host and registers it with the specified zone.
	HostInit(context.Context, *HostInitRequest) (*HostInitResponse, error)
	mustEmbedUnimplementedHostletServer()
}

// UnimplementedHostletServer must be embedded to have forward compatible implementations.
type UnimplementedHostletServer struct {
}

func (UnimplementedHostletServer) HostInit(context.Context, *HostInitRequest) (*HostInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostInit not implemented")
}
func (UnimplementedHostletServer) mustEmbedUnimplementedHostletServer() {}

// UnsafeHostletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostletServer will
// result in compilation errors.
type UnsafeHostletServer interface {
	mustEmbedUnimplementedHostletServer()
}

func RegisterHostletServer(s grpc.ServiceRegistrar, srv HostletServer) {
	s.RegisterService(&Hostlet_ServiceDesc, srv)
}

func _Hostlet_HostInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostletServer).HostInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hostlet_HostInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostletServer).HostInit(ctx, req.(*HostInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hostlet_ServiceDesc is the grpc.ServiceDesc for Hostlet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hostlet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.Hostlet",
	HandlerType: (*HostletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostInit",
			Handler:    _Hostlet_HostInit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	Zonelet_ZoneInit_FullMethodName          = "/inapi.Zonelet/ZoneInit"
	Zonelet_ZoneInfo_FullMethodName          = "/inapi.Zonelet/ZoneInfo"
	Zonelet_HostJoin_FullMethodName          = "/inapi.Zonelet/HostJoin"
	Zonelet_HostList_FullMethodName          = "/inapi.Zonelet/HostList"
	Zonelet_AppInstanceDeploy_FullMethodName = "/inapi.Zonelet/AppInstanceDeploy"
	Zonelet_AppInstanceInfo_FullMethodName   = "/inapi.Zonelet/AppInstanceInfo"
	Zonelet_AppInstanceList_FullMethodName   = "/inapi.Zonelet/AppInstanceList"
	Zonelet_AppInstanceDelete_FullMethodName = "/inapi.Zonelet/AppInstanceDelete"
	Zonelet_HostStatusUpdate_FullMethodName  = "/inapi.Zonelet/HostStatusUpdate"
	Zonelet_PackagePush_FullMethodName       = "/inapi.Zonelet/PackagePush"
	Zonelet_PackageList_FullMethodName       = "/inapi.Zonelet/PackageList"
)

// ZoneletClient is the client API for Zonelet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneletClient interface {
	// ZoneInit initializes a new zone with the specified name.
	ZoneInit(ctx context.Context, in *ZoneInitRequest, opts ...grpc.CallOption) (*ZoneInitResponse, error)
	// ZoneInfo retrieves information about the current zone.
	ZoneInfo(ctx context.Context, in *ZoneInfoRequest, opts ...grpc.CallOption) (*ZoneInfoResponse, error)
	// HostJoin registers a new host to join the zone.
	HostJoin(ctx context.Context, in *HostJoinRequest, opts ...grpc.CallOption) (*HostJoinResponse, error)
	// HostList retrieves all hosts in the zone.
	HostList(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error)
	// AppInstanceDeploy deploys a new application instance or updates an existing one.
	AppInstanceDeploy(ctx context.Context, in *AppInstanceDeployRequest, opts ...grpc.CallOption) (*AppInstanceDeployResponse, error)
	// AppInstanceInfo retrieves detailed information about a specific application instance.
	AppInstanceInfo(ctx context.Context, in *AppInstanceInfoRequest, opts ...grpc.CallOption) (*AppInstanceInfoResponse, error)
	// AppInstanceList retrieves all application instances in the zone.
	AppInstanceList(ctx context.Context, in *AppInstanceListRequest, opts ...grpc.CallOption) (*AppInstanceListResponse, error)
	// AppInstanceDelete deletes an application instance from the zone.
	AppInstanceDelete(ctx context.Context, in *AppInstanceDeleteRequest, opts ...grpc.CallOption) (*AppInstanceDeleteResponse, error)
	// HostStatusUpdate updates the status of a host and receives updated app instances.
	HostStatusUpdate(ctx context.Context, in *HostStatusUpdateRequest, opts ...grpc.CallOption) (*HostStatusUpdateResponse, error)
	// PackagePush uploads a package in chunks.
	PackagePush(ctx context.Context, in *PackagePushRequest, opts ...grpc.CallOption) (*PackagePushResponse, error)
	// PackageList retrieves all packages in the zone.
	PackageList(ctx context.Context, in *PackageListRequest, opts ...grpc.CallOption) (*PackageListResponse, error)
}

type zoneletClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneletClient(cc grpc.ClientConnInterface) ZoneletClient {
	return &zoneletClient{cc}
}

func (c *zoneletClient) ZoneInit(ctx context.Context, in *ZoneInitRequest, opts ...grpc.CallOption) (*ZoneInitResponse, error) {
	out := new(ZoneInitResponse)
	err := c.cc.Invoke(ctx, Zonelet_ZoneInit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) ZoneInfo(ctx context.Context, in *ZoneInfoRequest, opts ...grpc.CallOption) (*ZoneInfoResponse, error) {
	out := new(ZoneInfoResponse)
	err := c.cc.Invoke(ctx, Zonelet_ZoneInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) HostJoin(ctx context.Context, in *HostJoinRequest, opts ...grpc.CallOption) (*HostJoinResponse, error) {
	out := new(HostJoinResponse)
	err := c.cc.Invoke(ctx, Zonelet_HostJoin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) HostList(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error) {
	out := new(HostListResponse)
	err := c.cc.Invoke(ctx, Zonelet_HostList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) AppInstanceDeploy(ctx context.Context, in *AppInstanceDeployRequest, opts ...grpc.CallOption) (*AppInstanceDeployResponse, error) {
	out := new(AppInstanceDeployResponse)
	err := c.cc.Invoke(ctx, Zonelet_AppInstanceDeploy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) AppInstanceInfo(ctx context.Context, in *AppInstanceInfoRequest, opts ...grpc.CallOption) (*AppInstanceInfoResponse, error) {
	out := new(AppInstanceInfoResponse)
	err := c.cc.Invoke(ctx, Zonelet_AppInstanceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) AppInstanceList(ctx context.Context, in *AppInstanceListRequest, opts ...grpc.CallOption) (*AppInstanceListResponse, error) {
	out := new(AppInstanceListResponse)
	err := c.cc.Invoke(ctx, Zonelet_AppInstanceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) AppInstanceDelete(ctx context.Context, in *AppInstanceDeleteRequest, opts ...grpc.CallOption) (*AppInstanceDeleteResponse, error) {
	out := new(AppInstanceDeleteResponse)
	err := c.cc.Invoke(ctx, Zonelet_AppInstanceDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) HostStatusUpdate(ctx context.Context, in *HostStatusUpdateRequest, opts ...grpc.CallOption) (*HostStatusUpdateResponse, error) {
	out := new(HostStatusUpdateResponse)
	err := c.cc.Invoke(ctx, Zonelet_HostStatusUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) PackagePush(ctx context.Context, in *PackagePushRequest, opts ...grpc.CallOption) (*PackagePushResponse, error) {
	out := new(PackagePushResponse)
	err := c.cc.Invoke(ctx, Zonelet_PackagePush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneletClient) PackageList(ctx context.Context, in *PackageListRequest, opts ...grpc.CallOption) (*PackageListResponse, error) {
	out := new(PackageListResponse)
	err := c.cc.Invoke(ctx, Zonelet_PackageList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneletServer is the server API for Zonelet service.
// All implementations must embed UnimplementedZoneletServer
// for forward compatibility
type ZoneletServer interface {
	// ZoneInit initializes a new zone with the specified name.
	ZoneInit(context.Context, *ZoneInitRequest) (*ZoneInitResponse, error)
	// ZoneInfo retrieves information about the current zone.
	ZoneInfo(context.Context, *ZoneInfoRequest) (*ZoneInfoResponse, error)
	// HostJoin registers a new host to join the zone.
	HostJoin(context.Context, *HostJoinRequest) (*HostJoinResponse, error)
	// HostList retrieves all hosts in the zone.
	HostList(context.Context, *HostListRequest) (*HostListResponse, error)
	// AppInstanceDeploy deploys a new application instance or updates an existing one.
	AppInstanceDeploy(context.Context, *AppInstanceDeployRequest) (*AppInstanceDeployResponse, error)
	// AppInstanceInfo retrieves detailed information about a specific application instance.
	AppInstanceInfo(context.Context, *AppInstanceInfoRequest) (*AppInstanceInfoResponse, error)
	// AppInstanceList retrieves all application instances in the zone.
	AppInstanceList(context.Context, *AppInstanceListRequest) (*AppInstanceListResponse, error)
	// AppInstanceDelete deletes an application instance from the zone.
	AppInstanceDelete(context.Context, *AppInstanceDeleteRequest) (*AppInstanceDeleteResponse, error)
	// HostStatusUpdate updates the status of a host and receives updated app instances.
	HostStatusUpdate(context.Context, *HostStatusUpdateRequest) (*HostStatusUpdateResponse, error)
	// PackagePush uploads a package in chunks.
	PackagePush(context.Context, *PackagePushRequest) (*PackagePushResponse, error)
	// PackageList retrieves all packages in the zone.
	PackageList(context.Context, *PackageListRequest) (*PackageListResponse, error)
	mustEmbedUnimplementedZoneletServer()
}

// UnimplementedZoneletServer must be embedded to have forward compatible implementations.
type UnimplementedZoneletServer struct {
}

func (UnimplementedZoneletServer) ZoneInit(context.Context, *ZoneInitRequest) (*ZoneInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneInit not implemented")
}
func (UnimplementedZoneletServer) ZoneInfo(context.Context, *ZoneInfoRequest) (*ZoneInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneInfo not implemented")
}
func (UnimplementedZoneletServer) HostJoin(context.Context, *HostJoinRequest) (*HostJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostJoin not implemented")
}
func (UnimplementedZoneletServer) HostList(context.Context, *HostListRequest) (*HostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostList not implemented")
}
func (UnimplementedZoneletServer) AppInstanceDeploy(context.Context, *AppInstanceDeployRequest) (*AppInstanceDeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceDeploy not implemented")
}
func (UnimplementedZoneletServer) AppInstanceInfo(context.Context, *AppInstanceInfoRequest) (*AppInstanceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceInfo not implemented")
}
func (UnimplementedZoneletServer) AppInstanceList(context.Context, *AppInstanceListRequest) (*AppInstanceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceList not implemented")
}
func (UnimplementedZoneletServer) AppInstanceDelete(context.Context, *AppInstanceDeleteRequest) (*AppInstanceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceDelete not implemented")
}
func (UnimplementedZoneletServer) HostStatusUpdate(context.Context, *HostStatusUpdateRequest) (*HostStatusUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostStatusUpdate not implemented")
}
func (UnimplementedZoneletServer) PackagePush(context.Context, *PackagePushRequest) (*PackagePushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackagePush not implemented")
}
func (UnimplementedZoneletServer) PackageList(context.Context, *PackageListRequest) (*PackageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageList not implemented")
}
func (UnimplementedZoneletServer) mustEmbedUnimplementedZoneletServer() {}

// UnsafeZoneletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneletServer will
// result in compilation errors.
type UnsafeZoneletServer interface {
	mustEmbedUnimplementedZoneletServer()
}

func RegisterZoneletServer(s grpc.ServiceRegistrar, srv ZoneletServer) {
	s.RegisterService(&Zonelet_ServiceDesc, srv)
}

func _Zonelet_ZoneInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).ZoneInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_ZoneInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).ZoneInit(ctx, req.(*ZoneInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_ZoneInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).ZoneInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_ZoneInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).ZoneInfo(ctx, req.(*ZoneInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_HostJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).HostJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_HostJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).HostJoin(ctx, req.(*HostJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_HostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).HostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_HostList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).HostList(ctx, req.(*HostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_AppInstanceDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).AppInstanceDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_AppInstanceDeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).AppInstanceDeploy(ctx, req.(*AppInstanceDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_AppInstanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).AppInstanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_AppInstanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).AppInstanceInfo(ctx, req.(*AppInstanceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_AppInstanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).AppInstanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_AppInstanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).AppInstanceList(ctx, req.(*AppInstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_AppInstanceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).AppInstanceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_AppInstanceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).AppInstanceDelete(ctx, req.(*AppInstanceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_HostStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).HostStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_HostStatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).HostStatusUpdate(ctx, req.(*HostStatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_PackagePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackagePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).PackagePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_PackagePush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).PackagePush(ctx, req.(*PackagePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zonelet_PackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneletServer).PackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zonelet_PackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneletServer).PackageList(ctx, req.(*PackageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zonelet_ServiceDesc is the grpc.ServiceDesc for Zonelet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zonelet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.Zonelet",
	HandlerType: (*ZoneletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZoneInit",
			Handler:    _Zonelet_ZoneInit_Handler,
		},
		{
			MethodName: "ZoneInfo",
			Handler:    _Zonelet_ZoneInfo_Handler,
		},
		{
			MethodName: "HostJoin",
			Handler:    _Zonelet_HostJoin_Handler,
		},
		{
			MethodName: "HostList",
			Handler:    _Zonelet_HostList_Handler,
		},
		{
			MethodName: "AppInstanceDeploy",
			Handler:    _Zonelet_AppInstanceDeploy_Handler,
		},
		{
			MethodName: "AppInstanceInfo",
			Handler:    _Zonelet_AppInstanceInfo_Handler,
		},
		{
			MethodName: "AppInstanceList",
			Handler:    _Zonelet_AppInstanceList_Handler,
		},
		{
			MethodName: "AppInstanceDelete",
			Handler:    _Zonelet_AppInstanceDelete_Handler,
		},
		{
			MethodName: "HostStatusUpdate",
			Handler:    _Zonelet_HostStatusUpdate_Handler,
		},
		{
			MethodName: "PackagePush",
			Handler:    _Zonelet_PackagePush_Handler,
		},
		{
			MethodName: "PackageList",
			Handler:    _Zonelet_PackageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
