// Copyright 2015 Eryx <evorui аt gmаil dοt cοm>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package inapi

import (
	"fmt"
	"testing"
)

func TestContainerNameValid(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected bool
	}{
		// Valid cases
		{
			name:     "valid standard format",
			input:    "app-abc123def456-0001",
			expected: true,
		},
		{
			name:     "valid with underscore",
			input:    "app-my_app_123-00ff",
			expected: true,
		},
		{
			name:     "valid with hyphen in appId",
			input:    "app-my-app-123-abcd",
			expected: true,
		},
		{
			name:     "valid minimum appId length",
			input:    "app-abc-0000",
			expected: true,
		},
		{
			name:     "valid maximum appId length",
			input:    "app-abcdefghijklmnopqrstuvwxyz0123456789ABCD-ffff",
			expected: true,
		},
		{
			name:     "valid replica id max",
			input:    "app-testid-ffff",
			expected: true,
		},
		{
			name:     "valid replica id min",
			input:    "app-testid-0000",
			expected: true,
		},
		{
			name:     "valid alphanumeric mixed",
			input:    "app-A1b2C3d4E5f6-1a2b",
			expected: true,
		},

		// Invalid cases
		{
			name:     "invalid no prefix",
			input:    "abc123def456-0001",
			expected: false,
		},
		{
			name:     "invalid wrong prefix",
			input:    "container-abc123-0001",
			expected: false,
		},
		{
			name:     "invalid appId too short",
			input:    "app-ab-0001",
			expected: false,
		},
		{
			name:     "invalid appId too long",
			input:    "app-abcdefghijklmnopqrstuvwxyz0123456789ABCDE-0001",
			expected: false,
		},
		{
			name:     "invalid replica id uppercase",
			input:    "app-abc123-ABCD",
			expected: false,
		},
		{
			name:     "invalid replica id too short",
			input:    "app-abc123-001",
			expected: false,
		},
		{
			name:     "invalid replica id too long",
			input:    "app-abc123-00001",
			expected: false,
		},
		{
			name:     "invalid replica id non-hex",
			input:    "app-abc123-xyzg",
			expected: false,
		},
		{
			name:     "invalid special chars in appId",
			input:    "app-abc@123-0001",
			expected: false,
		},
		{
			name:     "invalid empty",
			input:    "",
			expected: false,
		},
		{
			name:     "invalid only prefix",
			input:    "app-",
			expected: false,
		},
		{
			name:     "invalid missing replica id",
			input:    "app-abc123",
			expected: false,
		},
		{
			name:     "invalid spaces",
			input:    "app-abc 123-0001",
			expected: false,
		},
		{
			name:     "invalid dots in appId",
			input:    "app-abc.123-0001",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := ContainerNameValid.MatchString(tt.input)
			if result != tt.expected {
				t.Errorf("ContainerNameValid.MatchString(%q) = %v, expected %v", tt.input, result, tt.expected)
			}
		})
	}
}

// TestContainerNameValidFormat tests that the regex correctly validates
// container names generated by the ContainerName() function format.
func TestContainerNameValidFormat(t *testing.T) {
	// Test the format pattern matches what ContainerName() generates
	// Format: app-{appId}-{replicaId:04x}

	tests := []struct {
		appId     string
		replicaId uint32
	}{
		{"abc123", 0},
		{"abc123", 1},
		{"abc123", 255},
		{"abc123", 4095},
		{"abc123", 65535},
		{"myapp789", 100},
		{"test-app-id", 999},
		{"APP_ID_123", 1234},
	}

	for _, tt := range tests {
		t.Run(fmt.Sprintf("appId=%s,replicaId=%d", tt.appId, tt.replicaId), func(t *testing.T) {
			// Simulate ContainerName() format
			containerName := fmt.Sprintf("app-%s-%04x", tt.appId, tt.replicaId)

			if !ContainerNameValid.MatchString(containerName) {
				t.Errorf("ContainerNameValid.MatchString(%q) = false, expected true", containerName)
			}
		})
	}
}
