// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.2
// source: app.proto

package inapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppInstance represents a deployed application instance in the cluster.
// It is the top-level resource that encapsulates the application specification,
// operational parameters, and current status.
type AppInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// meta contains the standard resource metadata (id, name, etc.).
	Meta *Metadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty" toml:"meta,omitempty"`
	// spec defines the desired state and configuration of the application.
	Spec *AppSpec `protobuf:"bytes,10,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty"`
	// deploy specifies the deployment parameters and desired actions.
	Deploy *AppDeploy `protobuf:"bytes,20,opt,name=deploy,proto3" json:"deploy,omitempty" toml:"deploy,omitempty"`
	// revision is an internal revision number for data synchronization.
	Revision uint64 `protobuf:"varint,21,opt,name=revision,proto3" json:"revision,omitempty" toml:"revision,omitempty"`
	// ref_by_instances records names of other app instances that reference
	// this instance as a dependency. Maintained by the zonelet to track
	// reverse dependency links.
	RefByInstances []string `protobuf:"bytes,22,rep,name=ref_by_instances,json=refByInstances,proto3" json:"ref_by_instances,omitempty" toml:"ref_by_instances,omitempty"`
}

func (x *AppInstance) Reset() {
	*x = AppInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInstance) ProtoMessage() {}

func (x *AppInstance) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInstance.ProtoReflect.Descriptor instead.
func (*AppInstance) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppInstance) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AppInstance) GetSpec() *AppSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AppInstance) GetDeploy() *AppDeploy {
	if x != nil {
		return x.Deploy
	}
	return nil
}

func (x *AppInstance) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AppInstance) GetRefByInstances() []string {
	if x != nil {
		return x.RefByInstances
	}
	return nil
}

// AppSpec defines the specification of an application, including its resources,
// services, executors, packages, dependencies, and configuration.
type AppSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// kind indicates the type of application (e.g., "app", "service").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	// name is the unique name of the application specification.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// version is the semantic version of the application specification,
	// following the SemVer format (e.g., "1.0.0", "2.1.3-beta").
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	// description provides a human-readable description of the application.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	// image specifies the container image to use (e.g., docker image).
	Image string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty" toml:"image,omitempty"`
	// resources defines the compute resource requirements and limits.
	Resources *AppSpecResources `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty" toml:"resources,omitempty"`
	// depends is a list of application-level dependencies.
	Depends []*AppSpecDepend `protobuf:"bytes,11,rep,name=depends,proto3" json:"depends,omitempty" toml:"depends,omitempty"`
	// service_depends is a list of service-level dependencies.
	ServiceDepends []*AppSpecDepend `protobuf:"bytes,12,rep,name=service_depends,json=serviceDepends,proto3" json:"service_depends,omitempty" toml:"service_depends,omitempty"`
	// service_ports is a list of service ports exposed by the application.
	ServicePorts []*AppSpecServicePort `protobuf:"bytes,13,rep,name=service_ports,json=servicePorts,proto3" json:"service_ports,omitempty" toml:"service_ports,omitempty"`
	// packages is a list of software packages required by the application.
	Packages []*AppSpecPackage `protobuf:"bytes,20,rep,name=packages,proto3" json:"packages,omitempty" toml:"packages,omitempty"`
	// configs defines the configuration schema for the application.
	Configs []*AppSpecConfigItem `protobuf:"bytes,21,rep,name=configs,proto3" json:"configs,omitempty" toml:"configs,omitempty"`
	// tasks is a list of tasks (commands/scripts) that run within the
	// application.
	Tasks []*AppSpecTask `protobuf:"bytes,30,rep,name=tasks,proto3" json:"tasks,omitempty" toml:"tasks,omitempty"`
}

func (x *AppSpec) Reset() {
	*x = AppSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpec) ProtoMessage() {}

func (x *AppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpec.ProtoReflect.Descriptor instead.
func (*AppSpec) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AppSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AppSpec) GetResources() *AppSpecResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AppSpec) GetDepends() []*AppSpecDepend {
	if x != nil {
		return x.Depends
	}
	return nil
}

func (x *AppSpec) GetServiceDepends() []*AppSpecDepend {
	if x != nil {
		return x.ServiceDepends
	}
	return nil
}

func (x *AppSpec) GetServicePorts() []*AppSpecServicePort {
	if x != nil {
		return x.ServicePorts
	}
	return nil
}

func (x *AppSpec) GetPackages() []*AppSpecPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *AppSpec) GetConfigs() []*AppSpecConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *AppSpec) GetTasks() []*AppSpecTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// AppSpecResources defines the resource allocation for an application.
type AppSpecResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cpu_limit specifies the maximum CPU resources allowed (e.g., "500m" for 0.5
	// cores).
	CpuLimit string `protobuf:"bytes,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty" toml:"cpu_limit,omitempty"`
	// memory_limit specifies the maximum memory resources allowed (e.g.,
	// "512Mi").
	MemoryLimit string `protobuf:"bytes,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty" toml:"memory_limit,omitempty"`
	// volume_limit specifies the maximum storage volume allowed (e.g., "10Gi").
	VolumeLimit string `protobuf:"bytes,4,opt,name=volume_limit,json=volumeLimit,proto3" json:"volume_limit,omitempty" toml:"volume_limit,omitempty"`
}

func (x *AppSpecResources) Reset() {
	*x = AppSpecResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecResources) ProtoMessage() {}

func (x *AppSpecResources) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecResources.ProtoReflect.Descriptor instead.
func (*AppSpecResources) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppSpecResources) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *AppSpecResources) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *AppSpecResources) GetVolumeLimit() string {
	if x != nil {
		return x.VolumeLimit
	}
	return ""
}

// AppSpecPackage represents a software package dependency.
type AppSpecPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the package.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// version specifies the required version of the package.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
}

func (x *AppSpecPackage) Reset() {
	*x = AppSpecPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecPackage) ProtoMessage() {}

func (x *AppSpecPackage) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecPackage.ProtoReflect.Descriptor instead.
func (*AppSpecPackage) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppSpecPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AppSpecDepend represents a dependency on another application or service.
type AppSpecDepend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the dependent application or service.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// version specifies the required version of the dependency.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
}

func (x *AppSpecDepend) Reset() {
	*x = AppSpecDepend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecDepend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecDepend) ProtoMessage() {}

func (x *AppSpecDepend) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecDepend.ProtoReflect.Descriptor instead.
func (*AppSpecDepend) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppSpecDepend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecDepend) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AppSpecServicePort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" toml:"port,omitempty"`
}

func (x *AppSpecServicePort) Reset() {
	*x = AppSpecServicePort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecServicePort) ProtoMessage() {}

func (x *AppSpecServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecServicePort.ProtoReflect.Descriptor instead.
func (*AppSpecServicePort) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppSpecServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// AppSpecTask defines a task execution entity with trigger logic and fault
// tolerance strategies.
type AppSpecTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the unique identifier of the task.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// working_dir specifies the working directory for command execution.
	WorkingDir string `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty" toml:"working_dir,omitempty"`
	// run_user specifies the user identity for command execution.
	RunUser string `protobuf:"bytes,3,opt,name=run_user,json=runUser,proto3" json:"run_user,omitempty" toml:"run_user,omitempty"`
	// depends_on is a list of task names that must complete successfully
	// before this task can run (used with trigger).
	DependsOn []string `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty" toml:"depends_on,omitempty"`
	// Trigger fields (mutually exclusive: only one should be set at a time):
	// - on_startup: triggers immediately when the application starts.
	// - on_shutdown: triggers before the application shuts down.
	// - interval_seconds: triggers periodically (every N seconds).
	// - cron: triggers on a schedule (standard cron expression).
	OnStartup       bool   `protobuf:"varint,10,opt,name=on_startup,json=onStartup,proto3" json:"on_startup,omitempty" toml:"on_startup,omitempty"`
	OnShutdown      bool   `protobuf:"varint,11,opt,name=on_shutdown,json=onShutdown,proto3" json:"on_shutdown,omitempty" toml:"on_shutdown,omitempty"`
	IntervalSeconds int64  `protobuf:"varint,12,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty" toml:"interval_seconds,omitempty"`
	Cron            string `protobuf:"bytes,13,opt,name=cron,proto3" json:"cron,omitempty" toml:"cron,omitempty"`
	// max_attempts is the maximum number of execution attempts (1 means no
	// retry).
	MaxAttempts uint32 `protobuf:"varint,20,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty" toml:"max_attempts,omitempty"`
	// retry_backoff_seconds is the interval/backoff time between retries.
	RetryBackoffSeconds uint32 `protobuf:"varint,21,opt,name=retry_backoff_seconds,json=retryBackoffSeconds,proto3" json:"retry_backoff_seconds,omitempty" toml:"retry_backoff_seconds,omitempty"`
	// script is the command or script to execute (split command and args to
	// prevent shell injection).
	Script string `protobuf:"bytes,30,opt,name=script,proto3" json:"script,omitempty" toml:"script,omitempty"`
}

func (x *AppSpecTask) Reset() {
	*x = AppSpecTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecTask) ProtoMessage() {}

func (x *AppSpecTask) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecTask.ProtoReflect.Descriptor instead.
func (*AppSpecTask) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppSpecTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecTask) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *AppSpecTask) GetRunUser() string {
	if x != nil {
		return x.RunUser
	}
	return ""
}

func (x *AppSpecTask) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *AppSpecTask) GetOnStartup() bool {
	if x != nil {
		return x.OnStartup
	}
	return false
}

func (x *AppSpecTask) GetOnShutdown() bool {
	if x != nil {
		return x.OnShutdown
	}
	return false
}

func (x *AppSpecTask) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *AppSpecTask) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *AppSpecTask) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *AppSpecTask) GetRetryBackoffSeconds() uint32 {
	if x != nil {
		return x.RetryBackoffSeconds
	}
	return 0
}

func (x *AppSpecTask) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// AppDeploy defines the deployment parameters and desired actions for an
// application.
type AppDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// action specifies the desired operation (manually set by user).
	// Valid values: start, stop, destroy.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	// revision is the operational revision for optimistic concurrency control.
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty" toml:"revision,omitempty"`
	// cpu_limit specifies the CPU limit in millicores (e.g., 500 = 0.5 cores).
	CpuLimit int64 `protobuf:"varint,10,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty" toml:"cpu_limit,omitempty"`
	// memory_limit specifies the memory limit in bytes.
	MemoryLimit int64 `protobuf:"varint,11,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty" toml:"memory_limit,omitempty"`
	// volume_limit specifies the volume limit in bytes.
	VolumeLimit int64 `protobuf:"varint,12,opt,name=volume_limit,json=volumeLimit,proto3" json:"volume_limit,omitempty" toml:"volume_limit,omitempty"`
	// configs is a list of deployment configs.
	Configs []*AppDeployConfigItem `protobuf:"bytes,13,rep,name=configs,proto3" json:"configs,omitempty" toml:"configs,omitempty"`
	// replica_cap specifies the desired number of replicas.
	ReplicaCap uint32 `protobuf:"varint,19,opt,name=replica_cap,json=replicaCap,proto3" json:"replica_cap,omitempty" toml:"replica_cap,omitempty"`
	// replicas is a list of replica deployment states.
	Replicas []*AppDeployReplica `protobuf:"bytes,20,rep,name=replicas,proto3" json:"replicas,omitempty" toml:"replicas,omitempty"`
	// depends is a list of resolved dependency bindings that map each
	// dependent AppSpec.Name to a concrete deployed AppInstance.Name.
	Depends []*AppDeployDepend `protobuf:"bytes,21,rep,name=depends,proto3" json:"depends,omitempty" toml:"depends,omitempty"`
}

func (x *AppDeploy) Reset() {
	*x = AppDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeploy) ProtoMessage() {}

func (x *AppDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeploy.ProtoReflect.Descriptor instead.
func (*AppDeploy) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{7}
}

func (x *AppDeploy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AppDeploy) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *AppDeploy) GetCpuLimit() int64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *AppDeploy) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *AppDeploy) GetVolumeLimit() int64 {
	if x != nil {
		return x.VolumeLimit
	}
	return 0
}

func (x *AppDeploy) GetConfigs() []*AppDeployConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *AppDeploy) GetReplicaCap() uint32 {
	if x != nil {
		return x.ReplicaCap
	}
	return 0
}

func (x *AppDeploy) GetReplicas() []*AppDeployReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *AppDeploy) GetDepends() []*AppDeployDepend {
	if x != nil {
		return x.Depends
	}
	return nil
}

// AppDeployConfigItem represents a single field in a deployment config.
type AppDeployConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// value is the value of the field.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty"`
	// type specifies the data type of the field.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty"`
	// items is a list of fields within this config group.
	Items []*AppDeployConfigItem `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
}

func (x *AppDeployConfigItem) Reset() {
	*x = AppDeployConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeployConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeployConfigItem) ProtoMessage() {}

func (x *AppDeployConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeployConfigItem.ProtoReflect.Descriptor instead.
func (*AppDeployConfigItem) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{8}
}

func (x *AppDeployConfigItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDeployConfigItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AppDeployConfigItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppDeployConfigItem) GetItems() []*AppDeployConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// AppDeployDepend represents a resolved dependency binding at deploy time.
// It maps an AppSpec.Name to a concrete deployed AppInstance.Name.
type AppDeployDepend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// spec_name is the name of the dependent application specification.
	SpecName string `protobuf:"bytes,1,opt,name=spec_name,json=specName,proto3" json:"spec_name,omitempty" toml:"spec_name,omitempty"`
	// instance_name is the name of the deployed app instance that satisfies
	// this dependency.
	InstanceName string `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty" toml:"instance_name,omitempty"`
	// 由调度器自动赋值
	Configs []*AppDeployConfigItem `protobuf:"bytes,13,rep,name=configs,proto3" json:"configs,omitempty" toml:"configs,omitempty"`
	// 由调度器自动赋值
	Replicas []*AppDeployReplica `protobuf:"bytes,20,rep,name=replicas,proto3" json:"replicas,omitempty" toml:"replicas,omitempty"`
}

func (x *AppDeployDepend) Reset() {
	*x = AppDeployDepend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeployDepend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeployDepend) ProtoMessage() {}

func (x *AppDeployDepend) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeployDepend.ProtoReflect.Descriptor instead.
func (*AppDeployDepend) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{9}
}

func (x *AppDeployDepend) GetSpecName() string {
	if x != nil {
		return x.SpecName
	}
	return ""
}

func (x *AppDeployDepend) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *AppDeployDepend) GetConfigs() []*AppDeployConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *AppDeployDepend) GetReplicas() []*AppDeployReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

// AppDeployReplica represents the deployment state of a replica.
type AppDeployReplica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the unique identifier of the replica.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	// host_id is the ID of the host where the replica runs.
	HostId   string `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty" toml:"host_id,omitempty"`
	HostIpv4 string `protobuf:"bytes,6,opt,name=host_ipv4,json=hostIpv4,proto3" json:"host_ipv4,omitempty" toml:"host_ipv4,omitempty"`
	// state is the desired state of the replica.
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty" toml:"state,omitempty"`
	// vpc_ipv4 is the VPC IPv4 address assigned to this replica by IPAM.
	VpcIpv4 string `protobuf:"bytes,4,opt,name=vpc_ipv4,json=vpcIpv4,proto3" json:"vpc_ipv4,omitempty" toml:"vpc_ipv4,omitempty"`
	// service_ports is the list of port mappings allocated for this replica.
	// Each entry maps a container port (box_port) to a host physical port
	// (host_port), assigned by the scheduler when the replica binds to a host.
	ServicePorts []*AppDeployServicePort `protobuf:"bytes,5,rep,name=service_ports,json=servicePorts,proto3" json:"service_ports,omitempty" toml:"service_ports,omitempty"`
}

func (x *AppDeployReplica) Reset() {
	*x = AppDeployReplica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeployReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeployReplica) ProtoMessage() {}

func (x *AppDeployReplica) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeployReplica.ProtoReflect.Descriptor instead.
func (*AppDeployReplica) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{10}
}

func (x *AppDeployReplica) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppDeployReplica) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AppDeployReplica) GetHostIpv4() string {
	if x != nil {
		return x.HostIpv4
	}
	return ""
}

func (x *AppDeployReplica) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AppDeployReplica) GetVpcIpv4() string {
	if x != nil {
		return x.VpcIpv4
	}
	return ""
}

func (x *AppDeployReplica) GetServicePorts() []*AppDeployServicePort {
	if x != nil {
		return x.ServicePorts
	}
	return nil
}

// AppDeployStage represents a single execution stage within the deployment
// lifecycle of an application. Stages can be nested to model complex,
// multi-level deployment workflows (e.g., a parent stage of "setup" may
// contain child stages such as "download", "configure", "start").
// Each stage tracks its owner, progress, attempt count and timing.
type AppDeployStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the identifier of the stage (e.g., "setup", "start", "healthcheck").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// owner indicates the component responsible for executing this stage
	// (e.g., "scheduler", "zonelet", "hostlet").
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty" toml:"owner,omitempty"`
	// state is the current execution status of the stage.
	// Valid values: pending, running, success, failed.
	State string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty" toml:"state,omitempty"`
	// attempt is the current retry count for this stage (0 means the first try).
	Attempt int64 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty" toml:"attempt,omitempty"`
	// attrs holds additional contextual key-value attributes for the stage,
	// such as intermediate results or driver-specific parameters.
	Attrs map[string]string `protobuf:"bytes,9,rep,name=attrs,proto3" json:"attrs,omitempty" toml:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// message carries human-readable execution details, such as progress
	// information or the last error description.
	Message string `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty" toml:"message,omitempty"`
	// created is the time the stage was created, as a unix timestamp in seconds.
	Created int64 `protobuf:"varint,14,opt,name=created,proto3" json:"created,omitempty" toml:"created,omitempty"`
	// finished is the time the stage reached a terminal state (success or
	// failure), as a unix timestamp in seconds. A value of 0 means the stage
	// is still pending or running.
	Finished int64 `protobuf:"varint,15,opt,name=finished,proto3" json:"finished,omitempty" toml:"finished,omitempty"`
	// stages is a list of nested child stages that make up this stage,
	// enabling hierarchical deployment workflows.
	Stages []*AppDeployStage `protobuf:"bytes,16,rep,name=stages,proto3" json:"stages,omitempty" toml:"stages,omitempty"`
}

func (x *AppDeployStage) Reset() {
	*x = AppDeployStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeployStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeployStage) ProtoMessage() {}

func (x *AppDeployStage) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeployStage.ProtoReflect.Descriptor instead.
func (*AppDeployStage) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{11}
}

func (x *AppDeployStage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDeployStage) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AppDeployStage) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AppDeployStage) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AppDeployStage) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *AppDeployStage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppDeployStage) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *AppDeployStage) GetFinished() int64 {
	if x != nil {
		return x.Finished
	}
	return 0
}

func (x *AppDeployStage) GetStages() []*AppDeployStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

// AppSpecConfigItem represents a single configuration field in the schema.
type AppSpecConfigItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the programmatic name of the field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// title is the human-readable title of the field.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty"`
	// prompt is a hint or placeholder text for the field.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty" toml:"prompt,omitempty"`
	// type specifies the data type of the field (e.g., "string", "number",
	// "bool").
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty"`
	// default is the default value of the field.
	Default string `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty" toml:"default,omitempty"`
	// auto_fill specifies an auto-fill expression or value.
	AutoFill string `protobuf:"bytes,6,opt,name=auto_fill,json=autoFill,proto3" json:"auto_fill,omitempty" toml:"auto_fill,omitempty"`
	// description provides a detailed description of the field.
	Description string               `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	Items       []*AppSpecConfigItem `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty"`
}

func (x *AppSpecConfigItem) Reset() {
	*x = AppSpecConfigItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppSpecConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecConfigItem) ProtoMessage() {}

func (x *AppSpecConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecConfigItem.ProtoReflect.Descriptor instead.
func (*AppSpecConfigItem) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{12}
}

func (x *AppSpecConfigItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpecConfigItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AppSpecConfigItem) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AppSpecConfigItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppSpecConfigItem) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *AppSpecConfigItem) GetAutoFill() string {
	if x != nil {
		return x.AutoFill
	}
	return ""
}

func (x *AppSpecConfigItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppSpecConfigItem) GetItems() []*AppSpecConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AppDeployServicePort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty" toml:"port,omitempty"`
	// host_port is the port number exposed on the host.
	HostPort uint32 `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty" toml:"host_port,omitempty"`
	// lan_addr is the LAN (local area network) address for internal access.
	LanAddr string `protobuf:"bytes,4,opt,name=lan_addr,json=lanAddr,proto3" json:"lan_addr,omitempty" toml:"lan_addr,omitempty"`
}

func (x *AppDeployServicePort) Reset() {
	*x = AppDeployServicePort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppDeployServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDeployServicePort) ProtoMessage() {}

func (x *AppDeployServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDeployServicePort.ProtoReflect.Descriptor instead.
func (*AppDeployServicePort) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{13}
}

func (x *AppDeployServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppDeployServicePort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppDeployServicePort) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *AppDeployServicePort) GetLanAddr() string {
	if x != nil {
		return x.LanAddr
	}
	return ""
}

type AppReplicaInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App            *AppInstance      `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty" toml:"app,omitempty"`
	Replica        *AppDeployReplica `protobuf:"bytes,2,opt,name=replica,proto3" json:"replica,omitempty" toml:"replica,omitempty"`
	ZoneBaseDomain string            `protobuf:"bytes,3,opt,name=zone_base_domain,json=zoneBaseDomain,proto3" json:"zone_base_domain,omitempty" toml:"zone_base_domain,omitempty"`
}

func (x *AppReplicaInstance) Reset() {
	*x = AppReplicaInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppReplicaInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReplicaInstance) ProtoMessage() {}

func (x *AppReplicaInstance) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReplicaInstance.ProtoReflect.Descriptor instead.
func (*AppReplicaInstance) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{14}
}

func (x *AppReplicaInstance) GetApp() *AppInstance {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *AppReplicaInstance) GetReplica() *AppDeployReplica {
	if x != nil {
		return x.Replica
	}
	return nil
}

func (x *AppReplicaInstance) GetZoneBaseDomain() string {
	if x != nil {
		return x.ZoneBaseDomain
	}
	return ""
}

var File_app_proto protoreflect.FileDescriptor

var file_app_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e, 0x61,
	0x70, 0x69, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc6, 0x01, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x28, 0x0a, 0x06, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x06, 0x64, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x28, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x66, 0x42, 0x79,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xfa, 0x03, 0x0a, 0x07, 0x41, 0x70,
	0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x35, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x07, 0x64,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x3d, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x18, 0x15, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x28, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x75, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70,
	0x75, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x70, 0x75, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3e, 0x0a,
	0x0e, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a,
	0x0d, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x12,
	0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xea, 0x02, 0x0a, 0x0b, 0x41,
	0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x73, 0x5f, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x4f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x6e, 0x5f, 0x73,
	0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f,
	0x6e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f,
	0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6d, 0x61, 0x78, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x5f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x72, 0x65, 0x74, 0x72,
	0x79, 0x42, 0x61, 0x63, 0x6b, 0x6f, 0x66, 0x66, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0xe0, 0x02, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x70,
	0x75, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x34, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x63, 0x61,
	0x70, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x43, 0x61, 0x70, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18,
	0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70,
	0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x08,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x73, 0x18, 0x15, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x07, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x41,
	0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x65, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x33,
	0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x76, 0x34, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x76, 0x34, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x70, 0x76, 0x34,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x70, 0x63, 0x49, 0x70, 0x76, 0x34, 0x12,
	0x40, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x73, 0x22, 0xdb, 0x02, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x36,
	0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xf2, 0x01, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x66, 0x69,
	0x6c, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x46, 0x69,
	0x6c, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x53,
	0x70, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x76, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x22, 0x97, 0x01, 0x0a,
	0x12, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x28, 0x0a, 0x10,
	0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x7a, 0x6f, 0x6e, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x69,
	0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData = file_app_proto_rawDesc
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_proto_rawDescData)
	})
	return file_app_proto_rawDescData
}

var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_app_proto_goTypes = []interface{}{
	(*AppInstance)(nil),          // 0: inapi.AppInstance
	(*AppSpec)(nil),              // 1: inapi.AppSpec
	(*AppSpecResources)(nil),     // 2: inapi.AppSpecResources
	(*AppSpecPackage)(nil),       // 3: inapi.AppSpecPackage
	(*AppSpecDepend)(nil),        // 4: inapi.AppSpecDepend
	(*AppSpecServicePort)(nil),   // 5: inapi.AppSpecServicePort
	(*AppSpecTask)(nil),          // 6: inapi.AppSpecTask
	(*AppDeploy)(nil),            // 7: inapi.AppDeploy
	(*AppDeployConfigItem)(nil),  // 8: inapi.AppDeployConfigItem
	(*AppDeployDepend)(nil),      // 9: inapi.AppDeployDepend
	(*AppDeployReplica)(nil),     // 10: inapi.AppDeployReplica
	(*AppDeployStage)(nil),       // 11: inapi.AppDeployStage
	(*AppSpecConfigItem)(nil),    // 12: inapi.AppSpecConfigItem
	(*AppDeployServicePort)(nil), // 13: inapi.AppDeployServicePort
	(*AppReplicaInstance)(nil),   // 14: inapi.AppReplicaInstance
	nil,                          // 15: inapi.AppDeployStage.AttrsEntry
	(*Metadata)(nil),             // 16: inapi.Metadata
}
var file_app_proto_depIdxs = []int32{
	16, // 0: inapi.AppInstance.meta:type_name -> inapi.Metadata
	1,  // 1: inapi.AppInstance.spec:type_name -> inapi.AppSpec
	7,  // 2: inapi.AppInstance.deploy:type_name -> inapi.AppDeploy
	2,  // 3: inapi.AppSpec.resources:type_name -> inapi.AppSpecResources
	4,  // 4: inapi.AppSpec.depends:type_name -> inapi.AppSpecDepend
	4,  // 5: inapi.AppSpec.service_depends:type_name -> inapi.AppSpecDepend
	5,  // 6: inapi.AppSpec.service_ports:type_name -> inapi.AppSpecServicePort
	3,  // 7: inapi.AppSpec.packages:type_name -> inapi.AppSpecPackage
	12, // 8: inapi.AppSpec.configs:type_name -> inapi.AppSpecConfigItem
	6,  // 9: inapi.AppSpec.tasks:type_name -> inapi.AppSpecTask
	8,  // 10: inapi.AppDeploy.configs:type_name -> inapi.AppDeployConfigItem
	10, // 11: inapi.AppDeploy.replicas:type_name -> inapi.AppDeployReplica
	9,  // 12: inapi.AppDeploy.depends:type_name -> inapi.AppDeployDepend
	8,  // 13: inapi.AppDeployConfigItem.items:type_name -> inapi.AppDeployConfigItem
	8,  // 14: inapi.AppDeployDepend.configs:type_name -> inapi.AppDeployConfigItem
	10, // 15: inapi.AppDeployDepend.replicas:type_name -> inapi.AppDeployReplica
	13, // 16: inapi.AppDeployReplica.service_ports:type_name -> inapi.AppDeployServicePort
	15, // 17: inapi.AppDeployStage.attrs:type_name -> inapi.AppDeployStage.AttrsEntry
	11, // 18: inapi.AppDeployStage.stages:type_name -> inapi.AppDeployStage
	12, // 19: inapi.AppSpecConfigItem.items:type_name -> inapi.AppSpecConfigItem
	0,  // 20: inapi.AppReplicaInstance.app:type_name -> inapi.AppInstance
	10, // 21: inapi.AppReplicaInstance.replica:type_name -> inapi.AppDeployReplica
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecDepend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecServicePort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeployConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeployDepend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeployReplica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeployStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppSpecConfigItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppDeployServicePort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppReplicaInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_rawDesc = nil
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
