// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.2
// source: gateway.proto

package inapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewayIngress is the user-facing model for managing an HTTP ingress entry
// bound to a domain with routing rules.
type GatewayIngress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// meta is the standard resource metadata (id, timestamps, version).
	Meta *Metadata `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty" toml:"meta,omitempty"`
	// domain is the fully qualified domain name for this ingress.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty" toml:"domain,omitempty"`
	// description is a human-readable description of this ingress.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	// options holds optional gateway features such as TLS.
	Options *GatewayIngress_Options `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty" toml:"options,omitempty"`
	// action is the ingress operation: "enable" (default) or "disable".
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	// routes are the HTTP routing rules for this domain.
	Routes []*GatewayIngress_HttpRoute `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty" toml:"routes,omitempty"`
}

func (x *GatewayIngress) Reset() {
	*x = GatewayIngress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngress) ProtoMessage() {}

func (x *GatewayIngress) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngress.ProtoReflect.Descriptor instead.
func (*GatewayIngress) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayIngress) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GatewayIngress) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GatewayIngress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GatewayIngress) GetOptions() *GatewayIngress_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GatewayIngress) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GatewayIngress) GetRoutes() []*GatewayIngress_HttpRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

// GatewayIngressDeploy is the flattened deployment model used by zonelet to
// configure the actual gateway proxy.
type GatewayIngressDeploy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the unique identifier of this deployment entry.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`
	// domain is the fully qualified domain name.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty" toml:"domain,omitempty"`
	// letsencrypt_enable enables automatic TLS provisioning via Let's Encrypt.
	LetsencryptEnable bool `protobuf:"varint,3,opt,name=letsencrypt_enable,json=letsencryptEnable,proto3" json:"letsencrypt_enable,omitempty" toml:"letsencrypt_enable,omitempty"`
	// routes are the HTTP routing rules for this domain.
	Routes []*GatewayIngressDeploy_HttpRoute `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty" toml:"routes,omitempty"`
	// revision is a monotonically increasing revision number for this deployment.
	Revision uint64 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty" toml:"revision,omitempty"`
}

func (x *GatewayIngressDeploy) Reset() {
	*x = GatewayIngressDeploy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngressDeploy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngressDeploy) ProtoMessage() {}

func (x *GatewayIngressDeploy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngressDeploy.ProtoReflect.Descriptor instead.
func (*GatewayIngressDeploy) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayIngressDeploy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GatewayIngressDeploy) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GatewayIngressDeploy) GetLetsencryptEnable() bool {
	if x != nil {
		return x.LetsencryptEnable
	}
	return false
}

func (x *GatewayIngressDeploy) GetRoutes() []*GatewayIngressDeploy_HttpRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GatewayIngressDeploy) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// HttpRoute maps a URL path to one or more upstream backends.
type GatewayIngress_HttpRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// path is the URL path to match, e.g. "/" or "/api/v1".
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" toml:"path,omitempty"`
	// type is the route type: "instance", "upstream", or "redirect".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty"`
	// action is the route operation: "enable" or "disable".
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	// targets are the upstream backends for this route.
	Targets []*GatewayIngress_HttpRoute_Target `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty" toml:"targets,omitempty"`
}

func (x *GatewayIngress_HttpRoute) Reset() {
	*x = GatewayIngress_HttpRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngress_HttpRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngress_HttpRoute) ProtoMessage() {}

func (x *GatewayIngress_HttpRoute) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngress_HttpRoute.ProtoReflect.Descriptor instead.
func (*GatewayIngress_HttpRoute) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GatewayIngress_HttpRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GatewayIngress_HttpRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GatewayIngress_HttpRoute) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GatewayIngress_HttpRoute) GetTargets() []*GatewayIngress_HttpRoute_Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Options holds optional gateway features.
type GatewayIngress_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// letsencrypt_enable enables automatic TLS certificate provisioning
	// via Let's Encrypt for this domain.
	LetsencryptEnable bool `protobuf:"varint,1,opt,name=letsencrypt_enable,json=letsencryptEnable,proto3" json:"letsencrypt_enable,omitempty" toml:"letsencrypt_enable,omitempty"`
}

func (x *GatewayIngress_Options) Reset() {
	*x = GatewayIngress_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngress_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngress_Options) ProtoMessage() {}

func (x *GatewayIngress_Options) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngress_Options.ProtoReflect.Descriptor instead.
func (*GatewayIngress_Options) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GatewayIngress_Options) GetLetsencryptEnable() bool {
	if x != nil {
		return x.LetsencryptEnable
	}
	return false
}

// Target is an upstream backend endpoint with an optional weight for
// load-balancing distribution.
type GatewayIngress_HttpRoute_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// backend is the backend endpoint, format depends on the route type:
	//
	//	instance  — AppInstance.ID:Port  (e.g. "a1b2c3d4e5f6:8080")
	//	upstream  — IPv4:Port            (e.g. "10.0.0.1:8080")
	//	redirect  — Full URL             (e.g. "https://example.com/path")
	Backend string `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty" toml:"backend,omitempty"`
	// weight is the traffic weight for load balancing (0 means equal share).
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty" toml:"weight,omitempty"`
}

func (x *GatewayIngress_HttpRoute_Target) Reset() {
	*x = GatewayIngress_HttpRoute_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngress_HttpRoute_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngress_HttpRoute_Target) ProtoMessage() {}

func (x *GatewayIngress_HttpRoute_Target) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngress_HttpRoute_Target.ProtoReflect.Descriptor instead.
func (*GatewayIngress_HttpRoute_Target) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GatewayIngress_HttpRoute_Target) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *GatewayIngress_HttpRoute_Target) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// HttpRoute is a simplified routing rule for deployment.
type GatewayIngressDeploy_HttpRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is the route type: "instance", "upstream", or "redirect".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" toml:"type,omitempty"`
	// path is the URL path to match.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty" toml:"path,omitempty"`
	// targets are the upstream backends for this route.
	Targets []*GatewayIngressDeploy_HttpRoute_Target `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty" toml:"targets,omitempty"`
}

func (x *GatewayIngressDeploy_HttpRoute) Reset() {
	*x = GatewayIngressDeploy_HttpRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngressDeploy_HttpRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngressDeploy_HttpRoute) ProtoMessage() {}

func (x *GatewayIngressDeploy_HttpRoute) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngressDeploy_HttpRoute.ProtoReflect.Descriptor instead.
func (*GatewayIngressDeploy_HttpRoute) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GatewayIngressDeploy_HttpRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GatewayIngressDeploy_HttpRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GatewayIngressDeploy_HttpRoute) GetTargets() []*GatewayIngressDeploy_HttpRoute_Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Target is an upstream backend endpoint with an optional weight for
// load-balancing distribution.
type GatewayIngressDeploy_HttpRoute_Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// backend is the backend endpoint (format depends on route type).
	Backend string `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty" toml:"backend,omitempty"`
	// weight is the traffic weight for load balancing (0 means equal share).
	Weight int32 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty" toml:"weight,omitempty"`
}

func (x *GatewayIngressDeploy_HttpRoute_Target) Reset() {
	*x = GatewayIngressDeploy_HttpRoute_Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayIngressDeploy_HttpRoute_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayIngressDeploy_HttpRoute_Target) ProtoMessage() {}

func (x *GatewayIngressDeploy_HttpRoute_Target) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayIngressDeploy_HttpRoute_Target.ProtoReflect.Descriptor instead.
func (*GatewayIngressDeploy_HttpRoute_Target) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GatewayIngressDeploy_HttpRoute_Target) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *GatewayIngressDeploy_HttpRoute_Target) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

var file_gateway_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x03, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x48,
	0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x1a, 0xc9, 0x01, 0x0a, 0x09, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40,
	0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73,
	0x1a, 0x3a, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x38, 0x0a, 0x07,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x6c, 0x65, 0x74, 0x73, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x6c, 0x65, 0x74, 0x73, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x82, 0x03, 0x0a, 0x14, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x6c, 0x65, 0x74, 0x73, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x11, 0x6c, 0x65, 0x74, 0x73, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0xb7, 0x01, 0x0a, 0x09, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x46, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x1a,
	0x3a, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x0c, 0x48, 0x03, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData = file_gateway_proto_rawDesc
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_proto_rawDescData)
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_proto_goTypes = []interface{}{
	(*GatewayIngress)(nil),                        // 0: inapi.GatewayIngress
	(*GatewayIngressDeploy)(nil),                  // 1: inapi.GatewayIngressDeploy
	(*GatewayIngress_HttpRoute)(nil),              // 2: inapi.GatewayIngress.HttpRoute
	(*GatewayIngress_Options)(nil),                // 3: inapi.GatewayIngress.Options
	(*GatewayIngress_HttpRoute_Target)(nil),       // 4: inapi.GatewayIngress.HttpRoute.Target
	(*GatewayIngressDeploy_HttpRoute)(nil),        // 5: inapi.GatewayIngressDeploy.HttpRoute
	(*GatewayIngressDeploy_HttpRoute_Target)(nil), // 6: inapi.GatewayIngressDeploy.HttpRoute.Target
	(*Metadata)(nil),                              // 7: inapi.Metadata
}
var file_gateway_proto_depIdxs = []int32{
	7, // 0: inapi.GatewayIngress.meta:type_name -> inapi.Metadata
	3, // 1: inapi.GatewayIngress.options:type_name -> inapi.GatewayIngress.Options
	2, // 2: inapi.GatewayIngress.routes:type_name -> inapi.GatewayIngress.HttpRoute
	5, // 3: inapi.GatewayIngressDeploy.routes:type_name -> inapi.GatewayIngressDeploy.HttpRoute
	4, // 4: inapi.GatewayIngress.HttpRoute.targets:type_name -> inapi.GatewayIngress.HttpRoute.Target
	6, // 5: inapi.GatewayIngressDeploy.HttpRoute.targets:type_name -> inapi.GatewayIngressDeploy.HttpRoute.Target
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngressDeploy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngress_HttpRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngress_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngress_HttpRoute_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngressDeploy_HttpRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayIngressDeploy_HttpRoute_Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_rawDesc = nil
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
