// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: service.proto

package inapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ZoneService_Ping_FullMethodName               = "/inapi.ZoneService/Ping"
	ZoneService_ZoneInit_FullMethodName           = "/inapi.ZoneService/ZoneInit"
	ZoneService_ZoneInfo_FullMethodName           = "/inapi.ZoneService/ZoneInfo"
	ZoneService_ZoneSet_FullMethodName            = "/inapi.ZoneService/ZoneSet"
	ZoneService_HostJoin_FullMethodName           = "/inapi.ZoneService/HostJoin"
	ZoneService_HostList_FullMethodName           = "/inapi.ZoneService/HostList"
	ZoneService_AppInstanceDeploy_FullMethodName  = "/inapi.ZoneService/AppInstanceDeploy"
	ZoneService_AppInstanceInfo_FullMethodName    = "/inapi.ZoneService/AppInstanceInfo"
	ZoneService_AppInstanceList_FullMethodName    = "/inapi.ZoneService/AppInstanceList"
	ZoneService_AppInstanceDelete_FullMethodName  = "/inapi.ZoneService/AppInstanceDelete"
	ZoneService_GatewayIngressInfo_FullMethodName = "/inapi.ZoneService/GatewayIngressInfo"
	ZoneService_GatewayIngressList_FullMethodName = "/inapi.ZoneService/GatewayIngressList"
	ZoneService_GatewayIngressSet_FullMethodName  = "/inapi.ZoneService/GatewayIngressSet"
	ZoneService_PackagePush_FullMethodName        = "/inapi.ZoneService/PackagePush"
	ZoneService_PackageList_FullMethodName        = "/inapi.ZoneService/PackageList"
	ZoneService_PackageDelete_FullMethodName      = "/inapi.ZoneService/PackageDelete"
)

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneServiceClient interface {
	// Ping checks server connectivity and authentication.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ZoneInit initializes a new zone with the specified name.
	ZoneInit(ctx context.Context, in *ZoneInitRequest, opts ...grpc.CallOption) (*ZoneInitResponse, error)
	// ZoneInfo retrieves information about the current zone.
	ZoneInfo(ctx context.Context, in *ZoneInfoRequest, opts ...grpc.CallOption) (*ZoneInfoResponse, error)
	// ZoneSet updates zone network configuration.
	// All three VPC fields (bridge, instance, domain) must be provided together.
	ZoneSet(ctx context.Context, in *ZoneSetRequest, opts ...grpc.CallOption) (*ZoneSetResponse, error)
	// HostJoin registers a new host to join the zone.
	HostJoin(ctx context.Context, in *HostJoinRequest, opts ...grpc.CallOption) (*HostJoinResponse, error)
	// HostList retrieves all hosts in the zone.
	HostList(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error)
	// AppInstanceDeploy deploys a new application instance or updates an
	// existing one.
	AppInstanceDeploy(ctx context.Context, in *AppInstanceDeployRequest, opts ...grpc.CallOption) (*AppInstanceDeployResponse, error)
	// AppInstanceInfo retrieves detailed information about a specific
	// application instance.
	AppInstanceInfo(ctx context.Context, in *AppInstanceInfoRequest, opts ...grpc.CallOption) (*AppInstanceInfoResponse, error)
	// AppInstanceList retrieves all application instances in the zone.
	AppInstanceList(ctx context.Context, in *AppInstanceListRequest, opts ...grpc.CallOption) (*AppInstanceListResponse, error)
	// AppInstanceDelete deletes an application instance from the zone.
	AppInstanceDelete(ctx context.Context, in *AppInstanceDeleteRequest, opts ...grpc.CallOption) (*AppInstanceDeleteResponse, error)
	// GatewayIngressInfo retrieves details of a specific gateway ingress.
	GatewayIngressInfo(ctx context.Context, in *GatewayIngressInfoRequest, opts ...grpc.CallOption) (*GatewayIngressInfoResponse, error)
	// GatewayIngressList retrieves all gateway ingress entries.
	GatewayIngressList(ctx context.Context, in *GatewayIngressListRequest, opts ...grpc.CallOption) (*GatewayIngressListResponse, error)
	// GatewayIngressSet creates or updates a gateway ingress entry.
	GatewayIngressSet(ctx context.Context, in *GatewayIngressSetRequest, opts ...grpc.CallOption) (*GatewayIngressSetResponse, error)
	// PackagePush uploads a package in chunks.
	PackagePush(ctx context.Context, in *PackagePushRequest, opts ...grpc.CallOption) (*PackagePushResponse, error)
	// PackageList retrieves all packages in the zone.
	PackageList(ctx context.Context, in *PackageListRequest, opts ...grpc.CallOption) (*PackageListResponse, error)
	// PackageDelete deletes a package and all its chunks from the zone.
	PackageDelete(ctx context.Context, in *PackageDeleteRequest, opts ...grpc.CallOption) (*PackageDeleteResponse, error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ZoneService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneInit(ctx context.Context, in *ZoneInitRequest, opts ...grpc.CallOption) (*ZoneInitResponse, error) {
	out := new(ZoneInitResponse)
	err := c.cc.Invoke(ctx, ZoneService_ZoneInit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneInfo(ctx context.Context, in *ZoneInfoRequest, opts ...grpc.CallOption) (*ZoneInfoResponse, error) {
	out := new(ZoneInfoResponse)
	err := c.cc.Invoke(ctx, ZoneService_ZoneInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ZoneSet(ctx context.Context, in *ZoneSetRequest, opts ...grpc.CallOption) (*ZoneSetResponse, error) {
	out := new(ZoneSetResponse)
	err := c.cc.Invoke(ctx, ZoneService_ZoneSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) HostJoin(ctx context.Context, in *HostJoinRequest, opts ...grpc.CallOption) (*HostJoinResponse, error) {
	out := new(HostJoinResponse)
	err := c.cc.Invoke(ctx, ZoneService_HostJoin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) HostList(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error) {
	out := new(HostListResponse)
	err := c.cc.Invoke(ctx, ZoneService_HostList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AppInstanceDeploy(ctx context.Context, in *AppInstanceDeployRequest, opts ...grpc.CallOption) (*AppInstanceDeployResponse, error) {
	out := new(AppInstanceDeployResponse)
	err := c.cc.Invoke(ctx, ZoneService_AppInstanceDeploy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AppInstanceInfo(ctx context.Context, in *AppInstanceInfoRequest, opts ...grpc.CallOption) (*AppInstanceInfoResponse, error) {
	out := new(AppInstanceInfoResponse)
	err := c.cc.Invoke(ctx, ZoneService_AppInstanceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AppInstanceList(ctx context.Context, in *AppInstanceListRequest, opts ...grpc.CallOption) (*AppInstanceListResponse, error) {
	out := new(AppInstanceListResponse)
	err := c.cc.Invoke(ctx, ZoneService_AppInstanceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) AppInstanceDelete(ctx context.Context, in *AppInstanceDeleteRequest, opts ...grpc.CallOption) (*AppInstanceDeleteResponse, error) {
	out := new(AppInstanceDeleteResponse)
	err := c.cc.Invoke(ctx, ZoneService_AppInstanceDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GatewayIngressInfo(ctx context.Context, in *GatewayIngressInfoRequest, opts ...grpc.CallOption) (*GatewayIngressInfoResponse, error) {
	out := new(GatewayIngressInfoResponse)
	err := c.cc.Invoke(ctx, ZoneService_GatewayIngressInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GatewayIngressList(ctx context.Context, in *GatewayIngressListRequest, opts ...grpc.CallOption) (*GatewayIngressListResponse, error) {
	out := new(GatewayIngressListResponse)
	err := c.cc.Invoke(ctx, ZoneService_GatewayIngressList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GatewayIngressSet(ctx context.Context, in *GatewayIngressSetRequest, opts ...grpc.CallOption) (*GatewayIngressSetResponse, error) {
	out := new(GatewayIngressSetResponse)
	err := c.cc.Invoke(ctx, ZoneService_GatewayIngressSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) PackagePush(ctx context.Context, in *PackagePushRequest, opts ...grpc.CallOption) (*PackagePushResponse, error) {
	out := new(PackagePushResponse)
	err := c.cc.Invoke(ctx, ZoneService_PackagePush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) PackageList(ctx context.Context, in *PackageListRequest, opts ...grpc.CallOption) (*PackageListResponse, error) {
	out := new(PackageListResponse)
	err := c.cc.Invoke(ctx, ZoneService_PackageList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) PackageDelete(ctx context.Context, in *PackageDeleteRequest, opts ...grpc.CallOption) (*PackageDeleteResponse, error) {
	out := new(PackageDeleteResponse)
	err := c.cc.Invoke(ctx, ZoneService_PackageDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServiceServer is the server API for ZoneService service.
// All implementations must embed UnimplementedZoneServiceServer
// for forward compatibility
type ZoneServiceServer interface {
	// Ping checks server connectivity and authentication.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ZoneInit initializes a new zone with the specified name.
	ZoneInit(context.Context, *ZoneInitRequest) (*ZoneInitResponse, error)
	// ZoneInfo retrieves information about the current zone.
	ZoneInfo(context.Context, *ZoneInfoRequest) (*ZoneInfoResponse, error)
	// ZoneSet updates zone network configuration.
	// All three VPC fields (bridge, instance, domain) must be provided together.
	ZoneSet(context.Context, *ZoneSetRequest) (*ZoneSetResponse, error)
	// HostJoin registers a new host to join the zone.
	HostJoin(context.Context, *HostJoinRequest) (*HostJoinResponse, error)
	// HostList retrieves all hosts in the zone.
	HostList(context.Context, *HostListRequest) (*HostListResponse, error)
	// AppInstanceDeploy deploys a new application instance or updates an
	// existing one.
	AppInstanceDeploy(context.Context, *AppInstanceDeployRequest) (*AppInstanceDeployResponse, error)
	// AppInstanceInfo retrieves detailed information about a specific
	// application instance.
	AppInstanceInfo(context.Context, *AppInstanceInfoRequest) (*AppInstanceInfoResponse, error)
	// AppInstanceList retrieves all application instances in the zone.
	AppInstanceList(context.Context, *AppInstanceListRequest) (*AppInstanceListResponse, error)
	// AppInstanceDelete deletes an application instance from the zone.
	AppInstanceDelete(context.Context, *AppInstanceDeleteRequest) (*AppInstanceDeleteResponse, error)
	// GatewayIngressInfo retrieves details of a specific gateway ingress.
	GatewayIngressInfo(context.Context, *GatewayIngressInfoRequest) (*GatewayIngressInfoResponse, error)
	// GatewayIngressList retrieves all gateway ingress entries.
	GatewayIngressList(context.Context, *GatewayIngressListRequest) (*GatewayIngressListResponse, error)
	// GatewayIngressSet creates or updates a gateway ingress entry.
	GatewayIngressSet(context.Context, *GatewayIngressSetRequest) (*GatewayIngressSetResponse, error)
	// PackagePush uploads a package in chunks.
	PackagePush(context.Context, *PackagePushRequest) (*PackagePushResponse, error)
	// PackageList retrieves all packages in the zone.
	PackageList(context.Context, *PackageListRequest) (*PackageListResponse, error)
	// PackageDelete deletes a package and all its chunks from the zone.
	PackageDelete(context.Context, *PackageDeleteRequest) (*PackageDeleteResponse, error)
	mustEmbedUnimplementedZoneServiceServer()
}

// UnimplementedZoneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedZoneServiceServer struct {
}

func (UnimplementedZoneServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedZoneServiceServer) ZoneInit(context.Context, *ZoneInitRequest) (*ZoneInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneInit not implemented")
}
func (UnimplementedZoneServiceServer) ZoneInfo(context.Context, *ZoneInfoRequest) (*ZoneInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneInfo not implemented")
}
func (UnimplementedZoneServiceServer) ZoneSet(context.Context, *ZoneSetRequest) (*ZoneSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZoneSet not implemented")
}
func (UnimplementedZoneServiceServer) HostJoin(context.Context, *HostJoinRequest) (*HostJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostJoin not implemented")
}
func (UnimplementedZoneServiceServer) HostList(context.Context, *HostListRequest) (*HostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostList not implemented")
}
func (UnimplementedZoneServiceServer) AppInstanceDeploy(context.Context, *AppInstanceDeployRequest) (*AppInstanceDeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceDeploy not implemented")
}
func (UnimplementedZoneServiceServer) AppInstanceInfo(context.Context, *AppInstanceInfoRequest) (*AppInstanceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceInfo not implemented")
}
func (UnimplementedZoneServiceServer) AppInstanceList(context.Context, *AppInstanceListRequest) (*AppInstanceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceList not implemented")
}
func (UnimplementedZoneServiceServer) AppInstanceDelete(context.Context, *AppInstanceDeleteRequest) (*AppInstanceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppInstanceDelete not implemented")
}
func (UnimplementedZoneServiceServer) GatewayIngressInfo(context.Context, *GatewayIngressInfoRequest) (*GatewayIngressInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayIngressInfo not implemented")
}
func (UnimplementedZoneServiceServer) GatewayIngressList(context.Context, *GatewayIngressListRequest) (*GatewayIngressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayIngressList not implemented")
}
func (UnimplementedZoneServiceServer) GatewayIngressSet(context.Context, *GatewayIngressSetRequest) (*GatewayIngressSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayIngressSet not implemented")
}
func (UnimplementedZoneServiceServer) PackagePush(context.Context, *PackagePushRequest) (*PackagePushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackagePush not implemented")
}
func (UnimplementedZoneServiceServer) PackageList(context.Context, *PackageListRequest) (*PackageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageList not implemented")
}
func (UnimplementedZoneServiceServer) PackageDelete(context.Context, *PackageDeleteRequest) (*PackageDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageDelete not implemented")
}
func (UnimplementedZoneServiceServer) mustEmbedUnimplementedZoneServiceServer() {}

// UnsafeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServiceServer will
// result in compilation errors.
type UnsafeZoneServiceServer interface {
	mustEmbedUnimplementedZoneServiceServer()
}

func RegisterZoneServiceServer(s grpc.ServiceRegistrar, srv ZoneServiceServer) {
	s.RegisterService(&ZoneService_ServiceDesc, srv)
}

func _ZoneService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ZoneInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneInit(ctx, req.(*ZoneInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ZoneInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneInfo(ctx, req.(*ZoneInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ZoneSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ZoneSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ZoneSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ZoneSet(ctx, req.(*ZoneSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_HostJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).HostJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_HostJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).HostJoin(ctx, req.(*HostJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_HostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).HostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_HostList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).HostList(ctx, req.(*HostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AppInstanceDeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AppInstanceDeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AppInstanceDeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AppInstanceDeploy(ctx, req.(*AppInstanceDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AppInstanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AppInstanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AppInstanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AppInstanceInfo(ctx, req.(*AppInstanceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AppInstanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AppInstanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AppInstanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AppInstanceList(ctx, req.(*AppInstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_AppInstanceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInstanceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).AppInstanceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_AppInstanceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).AppInstanceDelete(ctx, req.(*AppInstanceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GatewayIngressInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayIngressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GatewayIngressInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GatewayIngressInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GatewayIngressInfo(ctx, req.(*GatewayIngressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GatewayIngressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayIngressListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GatewayIngressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GatewayIngressList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GatewayIngressList(ctx, req.(*GatewayIngressListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GatewayIngressSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayIngressSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GatewayIngressSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GatewayIngressSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GatewayIngressSet(ctx, req.(*GatewayIngressSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_PackagePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackagePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).PackagePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_PackagePush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).PackagePush(ctx, req.(*PackagePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_PackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).PackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_PackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).PackageList(ctx, req.(*PackageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_PackageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).PackageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_PackageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).PackageDelete(ctx, req.(*PackageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneService_ServiceDesc is the grpc.ServiceDesc for ZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ZoneService_Ping_Handler,
		},
		{
			MethodName: "ZoneInit",
			Handler:    _ZoneService_ZoneInit_Handler,
		},
		{
			MethodName: "ZoneInfo",
			Handler:    _ZoneService_ZoneInfo_Handler,
		},
		{
			MethodName: "ZoneSet",
			Handler:    _ZoneService_ZoneSet_Handler,
		},
		{
			MethodName: "HostJoin",
			Handler:    _ZoneService_HostJoin_Handler,
		},
		{
			MethodName: "HostList",
			Handler:    _ZoneService_HostList_Handler,
		},
		{
			MethodName: "AppInstanceDeploy",
			Handler:    _ZoneService_AppInstanceDeploy_Handler,
		},
		{
			MethodName: "AppInstanceInfo",
			Handler:    _ZoneService_AppInstanceInfo_Handler,
		},
		{
			MethodName: "AppInstanceList",
			Handler:    _ZoneService_AppInstanceList_Handler,
		},
		{
			MethodName: "AppInstanceDelete",
			Handler:    _ZoneService_AppInstanceDelete_Handler,
		},
		{
			MethodName: "GatewayIngressInfo",
			Handler:    _ZoneService_GatewayIngressInfo_Handler,
		},
		{
			MethodName: "GatewayIngressList",
			Handler:    _ZoneService_GatewayIngressList_Handler,
		},
		{
			MethodName: "GatewayIngressSet",
			Handler:    _ZoneService_GatewayIngressSet_Handler,
		},
		{
			MethodName: "PackagePush",
			Handler:    _ZoneService_PackagePush_Handler,
		},
		{
			MethodName: "PackageList",
			Handler:    _ZoneService_PackageList_Handler,
		},
		{
			MethodName: "PackageDelete",
			Handler:    _ZoneService_PackageDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	ZoneInternalService_HostStatusUpdate_FullMethodName         = "/inapi.ZoneInternalService/HostStatusUpdate"
	ZoneInternalService_GatewayIngressDeployList_FullMethodName = "/inapi.ZoneInternalService/GatewayIngressDeployList"
	ZoneInternalService_PackageChunk_FullMethodName             = "/inapi.ZoneInternalService/PackageChunk"
)

// ZoneInternalServiceClient is the client API for ZoneInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneInternalServiceClient interface {
	// HostStatusUpdate updates the status of a host and receives updated app
	// instances.
	HostStatusUpdate(ctx context.Context, in *HostStatusUpdateRequest, opts ...grpc.CallOption) (*HostStatusUpdateResponse, error)
	// GatewayIngressDeployList retrieves deployed ingress entries newer than
	// the given version for incremental sync.
	GatewayIngressDeployList(ctx context.Context, in *GatewayIngressDeployListRequest, opts ...grpc.CallOption) (*GatewayIngressDeployListResponse, error)
	// PackageChunk retrieves a single chunk of a package for download.
	PackageChunk(ctx context.Context, in *PackageChunkRequest, opts ...grpc.CallOption) (*PackageChunkResponse, error)
}

type zoneInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneInternalServiceClient(cc grpc.ClientConnInterface) ZoneInternalServiceClient {
	return &zoneInternalServiceClient{cc}
}

func (c *zoneInternalServiceClient) HostStatusUpdate(ctx context.Context, in *HostStatusUpdateRequest, opts ...grpc.CallOption) (*HostStatusUpdateResponse, error) {
	out := new(HostStatusUpdateResponse)
	err := c.cc.Invoke(ctx, ZoneInternalService_HostStatusUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneInternalServiceClient) GatewayIngressDeployList(ctx context.Context, in *GatewayIngressDeployListRequest, opts ...grpc.CallOption) (*GatewayIngressDeployListResponse, error) {
	out := new(GatewayIngressDeployListResponse)
	err := c.cc.Invoke(ctx, ZoneInternalService_GatewayIngressDeployList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneInternalServiceClient) PackageChunk(ctx context.Context, in *PackageChunkRequest, opts ...grpc.CallOption) (*PackageChunkResponse, error) {
	out := new(PackageChunkResponse)
	err := c.cc.Invoke(ctx, ZoneInternalService_PackageChunk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneInternalServiceServer is the server API for ZoneInternalService service.
// All implementations must embed UnimplementedZoneInternalServiceServer
// for forward compatibility
type ZoneInternalServiceServer interface {
	// HostStatusUpdate updates the status of a host and receives updated app
	// instances.
	HostStatusUpdate(context.Context, *HostStatusUpdateRequest) (*HostStatusUpdateResponse, error)
	// GatewayIngressDeployList retrieves deployed ingress entries newer than
	// the given version for incremental sync.
	GatewayIngressDeployList(context.Context, *GatewayIngressDeployListRequest) (*GatewayIngressDeployListResponse, error)
	// PackageChunk retrieves a single chunk of a package for download.
	PackageChunk(context.Context, *PackageChunkRequest) (*PackageChunkResponse, error)
	mustEmbedUnimplementedZoneInternalServiceServer()
}

// UnimplementedZoneInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedZoneInternalServiceServer struct {
}

func (UnimplementedZoneInternalServiceServer) HostStatusUpdate(context.Context, *HostStatusUpdateRequest) (*HostStatusUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostStatusUpdate not implemented")
}
func (UnimplementedZoneInternalServiceServer) GatewayIngressDeployList(context.Context, *GatewayIngressDeployListRequest) (*GatewayIngressDeployListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayIngressDeployList not implemented")
}
func (UnimplementedZoneInternalServiceServer) PackageChunk(context.Context, *PackageChunkRequest) (*PackageChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageChunk not implemented")
}
func (UnimplementedZoneInternalServiceServer) mustEmbedUnimplementedZoneInternalServiceServer() {}

// UnsafeZoneInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneInternalServiceServer will
// result in compilation errors.
type UnsafeZoneInternalServiceServer interface {
	mustEmbedUnimplementedZoneInternalServiceServer()
}

func RegisterZoneInternalServiceServer(s grpc.ServiceRegistrar, srv ZoneInternalServiceServer) {
	s.RegisterService(&ZoneInternalService_ServiceDesc, srv)
}

func _ZoneInternalService_HostStatusUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStatusUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneInternalServiceServer).HostStatusUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneInternalService_HostStatusUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneInternalServiceServer).HostStatusUpdate(ctx, req.(*HostStatusUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneInternalService_GatewayIngressDeployList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayIngressDeployListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneInternalServiceServer).GatewayIngressDeployList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneInternalService_GatewayIngressDeployList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneInternalServiceServer).GatewayIngressDeployList(ctx, req.(*GatewayIngressDeployListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneInternalService_PackageChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneInternalServiceServer).PackageChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneInternalService_PackageChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneInternalServiceServer).PackageChunk(ctx, req.(*PackageChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneInternalService_ServiceDesc is the grpc.ServiceDesc for ZoneInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.ZoneInternalService",
	HandlerType: (*ZoneInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostStatusUpdate",
			Handler:    _ZoneInternalService_HostStatusUpdate_Handler,
		},
		{
			MethodName: "GatewayIngressDeployList",
			Handler:    _ZoneInternalService_GatewayIngressDeployList_Handler,
		},
		{
			MethodName: "PackageChunk",
			Handler:    _ZoneInternalService_PackageChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	HostInternalService_HostInit_FullMethodName = "/inapi.HostInternalService/HostInit"
)

// HostInternalServiceClient is the client API for HostInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostInternalServiceClient interface {
	// HostInit initializes a new host and registers it with the specified zone.
	HostInit(ctx context.Context, in *HostInitRequest, opts ...grpc.CallOption) (*HostInitResponse, error)
}

type hostInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostInternalServiceClient(cc grpc.ClientConnInterface) HostInternalServiceClient {
	return &hostInternalServiceClient{cc}
}

func (c *hostInternalServiceClient) HostInit(ctx context.Context, in *HostInitRequest, opts ...grpc.CallOption) (*HostInitResponse, error) {
	out := new(HostInitResponse)
	err := c.cc.Invoke(ctx, HostInternalService_HostInit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostInternalServiceServer is the server API for HostInternalService service.
// All implementations must embed UnimplementedHostInternalServiceServer
// for forward compatibility
type HostInternalServiceServer interface {
	// HostInit initializes a new host and registers it with the specified zone.
	HostInit(context.Context, *HostInitRequest) (*HostInitResponse, error)
	mustEmbedUnimplementedHostInternalServiceServer()
}

// UnimplementedHostInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHostInternalServiceServer struct {
}

func (UnimplementedHostInternalServiceServer) HostInit(context.Context, *HostInitRequest) (*HostInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostInit not implemented")
}
func (UnimplementedHostInternalServiceServer) mustEmbedUnimplementedHostInternalServiceServer() {}

// UnsafeHostInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostInternalServiceServer will
// result in compilation errors.
type UnsafeHostInternalServiceServer interface {
	mustEmbedUnimplementedHostInternalServiceServer()
}

func RegisterHostInternalServiceServer(s grpc.ServiceRegistrar, srv HostInternalServiceServer) {
	s.RegisterService(&HostInternalService_ServiceDesc, srv)
}

func _HostInternalService_HostInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostInternalServiceServer).HostInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostInternalService_HostInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostInternalServiceServer).HostInit(ctx, req.(*HostInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostInternalService_ServiceDesc is the grpc.ServiceDesc for HostInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inapi.HostInternalService",
	HandlerType: (*HostInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HostInit",
			Handler:    _HostInternalService_HostInit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
