// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.2
// source: zone.proto

package inapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zone represents a logical cluster or data center in the infrastructure.
// A zone contains multiple hosts and serves as a management boundary for
// resource allocation and application deployment.
type Zone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the unique identifier of the zone.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	// description provides a human-readable description of the zone.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	// action specifies the current action being performed on the zone.
	// Valid values: init, update, destroy.
	Action string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
	// hosts is a list of host IDs that belong to this zone.
	Hosts []string `protobuf:"bytes,9,rep,name=hosts,proto3" json:"hosts,omitempty" toml:"hosts,omitempty"`
	// vpc_bridge_cidr specifies the zone-wide VPC bridge subnet.
	//
	// Must be a private IPv4 /24 network (RFC 1918). Each host node is
	// assigned a bridge IP whose fourth octet falls within the allocatable
	// range [3, 252]. Octets 0-2 and 253-255 are reserved for system use.
	//
	//	Example: 192.168.10.0/24
	//	  192.168.10.3    -> host-1 bridge IP   (first allocatable)
	//	  ...
	//	  192.168.10.252  -> host-250 bridge IP  (last allocatable)
	//
	// Allocatable capacity: 250 host nodes per zone.
	VpcBridgeCidr string `protobuf:"bytes,10,opt,name=vpc_bridge_cidr,json=vpcBridgeCidr,proto3" json:"vpc_bridge_cidr,omitempty" toml:"vpc_bridge_cidr,omitempty"`
	// vpc_instance_cidr specifies the zone-wide VPC instance supernet.
	//
	// Must be a private IPv4 /16 network (RFC 1918). The /16 prefix length
	// provides a two-level hierarchy where the third octet (c) maps 1:1 to
	// a host node's bridge IP fourth octet, and the fourth octet (d)
	// provides per-host instance addresses:
	//
	//	a.b.c.d  ->  a.b.{host_index}.{instance_index}
	//
	// Both c and d are allocated within [3, 252] only. Octets 0-2 and 253-255
	// are reserved for future use.
	//
	//	Example: 10.10.0.0/16
	//	  10.10.3.0/24  -> instances on host with bridge 192.168.10.3
	//	    10.10.3.3   -> instance-1 (first allocatable)
	//	    ...
	//	    10.10.3.252 -> instance-250 (last allocatable)
	//	  ...
	//	  10.10.N.d     -> instance d on host N  (N, d in [3, 252])
	//
	// Allocatable capacity: 250 hosts * 250 instances/host = 62,500.
	//
	// The third octet of the instance subnet and the bridge subnet must
	// form a bijective mapping (c-instance <-> c-bridge) managed by the
	// internal IPAM scheduler.
	VpcInstanceCidr string `protobuf:"bytes,11,opt,name=vpc_instance_cidr,json=vpcInstanceCidr,proto3" json:"vpc_instance_cidr,omitempty" toml:"vpc_instance_cidr,omitempty"`
	// vpc_network_domain is the DNS domain for VPC internal name resolution.
	// The internal DNS resolves <app-instance-id>.<domain> to the container
	// instance IP. Default: "local". Recommended: "zone-name.example.com".
	VpcNetworkDomain string `protobuf:"bytes,12,opt,name=vpc_network_domain,json=vpcNetworkDomain,proto3" json:"vpc_network_domain,omitempty" toml:"vpc_network_domain,omitempty"`
}

func (x *Zone) Reset() {
	*x = Zone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{0}
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Zone) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Zone) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Zone) GetVpcBridgeCidr() string {
	if x != nil {
		return x.VpcBridgeCidr
	}
	return ""
}

func (x *Zone) GetVpcInstanceCidr() string {
	if x != nil {
		return x.VpcInstanceCidr
	}
	return ""
}

func (x *Zone) GetVpcNetworkDomain() string {
	if x != nil {
		return x.VpcNetworkDomain
	}
	return ""
}

// ZoneNetworkMap represents the distributed routing table for VPC networking.
// It is generated by the zone leader and propagated to all hosts.
type ZoneNetworkMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// zone-wide VPC bridge subnet (e.g., "192.168.10.0/24")
	VpcBridgeCidr string `protobuf:"bytes,2,opt,name=vpc_bridge_cidr,json=vpcBridgeCidr,proto3" json:"vpc_bridge_cidr,omitempty" toml:"vpc_bridge_cidr,omitempty"`
	// zone-wide VPC instance supernet (e.g., "10.10.0.0/16")
	VpcInstanceCidr string `protobuf:"bytes,3,opt,name=vpc_instance_cidr,json=vpcInstanceCidr,proto3" json:"vpc_instance_cidr,omitempty" toml:"vpc_instance_cidr,omitempty"`
	// DNS domain for VPC name resolution
	VpcNetworkDomain string `protobuf:"bytes,4,opt,name=vpc_network_domain,json=vpcNetworkDomain,proto3" json:"vpc_network_domain,omitempty" toml:"vpc_network_domain,omitempty"`
	// vpc_bridge_host maps bridge IP to host network info.
	// Example: key=3232238090 -> host id "6985b60604d7", instance
	// subnet 10.10.2.0
	VpcBridgeHost map[uint32]*ZoneNetworkMap_Host `protobuf:"bytes,5,rep,name=vpc_bridge_host,json=vpcBridgeHost,proto3" json:"vpc_bridge_host,omitempty" toml:"vpc_bridge_host,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// vpc_instance maps instance IP last octet to replica ID.
	// Example: key corresponding to 10.10.2.3 -> "699e0d6f3f11-0000"
	VpcInstance map[uint32]string `protobuf:"bytes,7,rep,name=vpc_instance,json=vpcInstance,proto3" json:"vpc_instance,omitempty" toml:"vpc_instance,omitempty" protobuf_key:"fixed32,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// monotonic revision for incremental sync
	Revision uint64 `protobuf:"varint,8,opt,name=revision,proto3" json:"revision,omitempty" toml:"revision,omitempty"`
	// last update unix timestamp (seconds)
	Updated int64 `protobuf:"varint,13,opt,name=updated,proto3" json:"updated,omitempty" toml:"updated,omitempty"`
}

func (x *ZoneNetworkMap) Reset() {
	*x = ZoneNetworkMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneNetworkMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneNetworkMap) ProtoMessage() {}

func (x *ZoneNetworkMap) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneNetworkMap.ProtoReflect.Descriptor instead.
func (*ZoneNetworkMap) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneNetworkMap) GetVpcBridgeCidr() string {
	if x != nil {
		return x.VpcBridgeCidr
	}
	return ""
}

func (x *ZoneNetworkMap) GetVpcInstanceCidr() string {
	if x != nil {
		return x.VpcInstanceCidr
	}
	return ""
}

func (x *ZoneNetworkMap) GetVpcNetworkDomain() string {
	if x != nil {
		return x.VpcNetworkDomain
	}
	return ""
}

func (x *ZoneNetworkMap) GetVpcBridgeHost() map[uint32]*ZoneNetworkMap_Host {
	if x != nil {
		return x.VpcBridgeHost
	}
	return nil
}

func (x *ZoneNetworkMap) GetVpcInstance() map[uint32]string {
	if x != nil {
		return x.VpcInstance
	}
	return nil
}

func (x *ZoneNetworkMap) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ZoneNetworkMap) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// Host represents a host's VPC network identity within the routing table.
type ZoneNetworkMap_Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" toml:"id,omitempty"`               // host unique identifier
	Peer     uint32 `protobuf:"fixed32,2,opt,name=peer,proto3" json:"peer,omitempty" toml:"peer,omitempty"`         // peer address
	Bridge   uint32 `protobuf:"fixed32,3,opt,name=bridge,proto3" json:"bridge,omitempty" toml:"bridge,omitempty"`     // bridge address
	Instance uint32 `protobuf:"fixed32,4,opt,name=instance,proto3" json:"instance,omitempty" toml:"instance,omitempty"` // instance subnet address
}

func (x *ZoneNetworkMap_Host) Reset() {
	*x = ZoneNetworkMap_Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZoneNetworkMap_Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneNetworkMap_Host) ProtoMessage() {}

func (x *ZoneNetworkMap_Host) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneNetworkMap_Host.ProtoReflect.Descriptor instead.
func (*ZoneNetworkMap_Host) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ZoneNetworkMap_Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ZoneNetworkMap_Host) GetPeer() uint32 {
	if x != nil {
		return x.Peer
	}
	return 0
}

func (x *ZoneNetworkMap_Host) GetBridge() uint32 {
	if x != nil {
		return x.Bridge
	}
	return 0
}

func (x *ZoneNetworkMap_Host) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

var File_zone_proto protoreflect.FileDescriptor

var file_zone_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x7a, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x22, 0xec, 0x01, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73,
	0x12, 0x26, 0x0a, 0x0f, 0x76, 0x70, 0x63, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x63,
	0x69, 0x64, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x70, 0x63, 0x42, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x43, 0x69, 0x64, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x76, 0x70, 0x63, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x70, 0x63, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x43, 0x69, 0x64, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x76, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x76, 0x70, 0x63, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0xe3, 0x04, 0x0a, 0x0e, 0x5a, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x4d, 0x61, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x76, 0x70, 0x63, 0x5f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x76, 0x70, 0x63, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x43, 0x69, 0x64, 0x72, 0x12, 0x2a, 0x0a,
	0x11, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x69,
	0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x70, 0x63, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x69, 0x64, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x76, 0x70, 0x63,
	0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x76, 0x70, 0x63, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x50, 0x0a, 0x0f, 0x76, 0x70, 0x63, 0x5f, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x2e, 0x56, 0x70, 0x63, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x48, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x76, 0x70, 0x63, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x0c, 0x76, 0x70, 0x63,
	0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x2e, 0x56, 0x70, 0x63, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x76, 0x70, 0x63, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x5e, 0x0a, 0x04, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x5c, 0x0a, 0x12, 0x56, 0x70,
	0x63, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3e, 0x0a, 0x10, 0x56, 0x70, 0x63, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zone_proto_rawDescOnce sync.Once
	file_zone_proto_rawDescData = file_zone_proto_rawDesc
)

func file_zone_proto_rawDescGZIP() []byte {
	file_zone_proto_rawDescOnce.Do(func() {
		file_zone_proto_rawDescData = protoimpl.X.CompressGZIP(file_zone_proto_rawDescData)
	})
	return file_zone_proto_rawDescData
}

var file_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zone_proto_goTypes = []interface{}{
	(*Zone)(nil),                // 0: inapi.Zone
	(*ZoneNetworkMap)(nil),      // 1: inapi.ZoneNetworkMap
	(*ZoneNetworkMap_Host)(nil), // 2: inapi.ZoneNetworkMap.Host
	nil,                         // 3: inapi.ZoneNetworkMap.VpcBridgeHostEntry
	nil,                         // 4: inapi.ZoneNetworkMap.VpcInstanceEntry
}
var file_zone_proto_depIdxs = []int32{
	3, // 0: inapi.ZoneNetworkMap.vpc_bridge_host:type_name -> inapi.ZoneNetworkMap.VpcBridgeHostEntry
	4, // 1: inapi.ZoneNetworkMap.vpc_instance:type_name -> inapi.ZoneNetworkMap.VpcInstanceEntry
	2, // 2: inapi.ZoneNetworkMap.VpcBridgeHostEntry.value:type_name -> inapi.ZoneNetworkMap.Host
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zone_proto_init() }
func file_zone_proto_init() {
	if File_zone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneNetworkMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZoneNetworkMap_Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zone_proto_goTypes,
		DependencyIndexes: file_zone_proto_depIdxs,
		MessageInfos:      file_zone_proto_msgTypes,
	}.Build()
	File_zone_proto = out.File
	file_zone_proto_rawDesc = nil
	file_zone_proto_goTypes = nil
	file_zone_proto_depIdxs = nil
}
