#!/bin/bash

set -e

VERSION=v1.0

docker pull --platform linux/amd64 alpine:3.20.8

docker build --platform linux/amd64 -f Dockerfile_${VERSION} -t sysinner/innerstack-b1:${VERSION} .

# docker run --rm -it -p 2022:2022 --platform linux/amd64 sysinner/innerstack-b1:${VERSION} /bin/sh

