


HISTCONTROL=ignoreboth
shopt -s histappend

HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize


export PS1='\[\e[1;32m\][\u@los-soho \W]\$\[\e[0m\] '

export LANG=en_US.UTF-8
export TERM=linux

if [ `uname` = Linux ]; then
    alias ls='ls --color'
    alias ll='ls -l'
fi

TMOUT=3600


