// Copyright 2015 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package hostapi

import (
	"context"
	"fmt"
	"log/slog"
	"regexp"
	"sync"

	"github.com/sysinner/innerstack/v2/pkg/inapi"
)

var (
	// ContainerNameValid validates container names generated by ContainerName().
	// Format: i8k_{instanceName}_{replicaId}
	// Example: i8k_myapp_1
	// - Prefix: "i8k_"
	// - InstanceName: DNS label (lowercase alphanumeric and hyphens)
	// - ReplicaId: decimal integer, 1-3 digits (range 0-127, ReplicaCap <= AppReplicaCapMax)
	ContainerNameValid = regexp.MustCompile(`^i8k_[a-z0-9]([-a-z0-9]*[a-z0-9])?_[0-9]{1,3}$`)
)

type AppReplicaInstanceList struct {
	mu    sync.RWMutex
	index map[string]*inapi.AppReplicaInstance
}

func (it *AppReplicaInstanceList) TryStore(rep *inapi.AppReplicaInstance) bool {
	it.mu.Lock()
	defer it.mu.Unlock()
	if it.index == nil {
		it.index = map[string]*inapi.AppReplicaInstance{}
	}
	item, ok := it.index[rep.ContainerName()]
	if !ok || rep.App.Deploy.Revision > item.App.Deploy.Revision {
		if ok {
			slog.Info(fmt.Sprintf("app-deploy %s revision %d -> %d",
				rep.ContainerName(), item.App.Deploy.Revision, rep.App.Deploy.Revision))
		} else {
			slog.Info(fmt.Sprintf("app-deploy %s revision %d",
				rep.ContainerName(), rep.App.Deploy.Revision))
		}
		it.index[rep.ContainerName()] = rep
		return true
	}
	return false
}

// DriverInfo represents container driver metadata.
type DriverInfo struct {
	Name         string `json:"name"`
	Version      string `json:"version"`
	APIVersion   string `json:"api_version,omitempty"`
	OS           string `json:"os,omitempty"`
	Arch         string `json:"arch,omitempty"`
	Kernel       string `json:"kernel,omitempty"`
	ContainerNum int    `json:"container_num,omitempty"`
	ImageNum     int    `json:"image_num,omitempty"`
}

// ContainerInfo represents container instance details.
type ContainerInfo struct {
	ID          string                `json:"id"`
	Name        string                `json:"name"`
	Image       string                `json:"image"`
	ImageID     string                `json:"image_id"`
	State       string                `json:"state"`             // running, exited, paused, etc.
	Status      string                `json:"status"`            // detailed status
	Pid         int                   `json:"pid"`               // process ID
	IP          string                `json:"ip"`                // container IP
	Ports       map[int32]PortBinding `json:"ports"`             // port mappings (key: container port)
	Created     int64                 `json:"created"`           // unix timestamp (seconds)
	Started     int64                 `json:"started,omitempty"` // unix timestamp (seconds)
	Labels      map[string]string     `json:"labels,omitempty"`
	CpuLimit    int64                 `json:"cpu_limit,omitempty"`    // CPU limit (millicores)
	MemoryLimit int64                 `json:"memory_limit,omitempty"` // memory limit (bytes)
	Binds       []string              `json:"binds,omitempty"`        // volume binds from HostConfig

	LastInspectTime int64 `json:"-"`
}

// PortBinding represents a port mapping configuration.
type PortBinding struct {
	HostIP        string `json:"host_ip"`
	HostPort      int32  `json:"host_port"`
	ContainerPort int32  `json:"container_port"`
	Protocol      string `json:"protocol"` // tcp, udp
}

// MountBind represents a directory mount configuration.
type MountBind struct {
	HostPath      string `json:"host_path"`      // host path
	ContainerPath string `json:"container_path"` // container path
	ReadOnly      bool   `json:"read_only"`      // read-only flag
	UID           int    `json:"uid,omitempty"`  // user id for chown (0 means no change)
	GID           int    `json:"gid,omitempty"`  // group id for chown (0 means no change)
}

// ImageInfo represents container image metadata.
type ImageInfo struct {
	Name        string            `json:"name"`
	ID          string            `json:"id"`
	RepoTags    []string          `json:"repo_tags"`
	RepoDigests []string          `json:"repo_digests"`
	Size        int64             `json:"size"`    // bytes
	Created     int64             `json:"created"` // unix timestamp (seconds)
	Labels      map[string]string `json:"labels,omitempty"`
}

// ContainerCreateOptions defines container creation parameters.
type ContainerCreateOptions struct {
	Name          string            // container name
	Image         string            // image name
	Cmd           []string          // entrypoint command
	Env           []string          // environment variables
	Labels        map[string]string // metadata labels
	Hostname      string            // container hostname
	CpuLimit      int64             // CPU limit (millicores, 1000 = 1 core)
	MemoryLimit   int64             // memory limit (bytes)
	Ports         []PortBinding     // port mappings
	Mounts        []MountBind       // volume mounts
	RestartPolicy string            // no, always, on-failure, unless-stopped
	DnsServers    []string          // DNS servers for container
	VpcIPv4       string            // VPC IP to assign to container
	VpcSubnet     string            // VPC subnet CIDR for Docker network creation
}

// ContainerStats holds a snapshot of resource usage statistics for a container.
// CPU, network and block fields are cumulative counters since the container
// started; the caller derives rates via a sliding-window delta.
type ContainerStats struct {
	Time          int64 `json:"time"`            // unix timestamp (seconds)
	CpuTotalUsage int64 `json:"cpu_total_usage"` // CPU total usage (nanoseconds)
	CpuUser       int64 `json:"cpu_user"`        // CPU user-mode usage (nanoseconds)
	CpuSystem     int64 `json:"cpu_system"`      // CPU kernel-mode usage (nanoseconds)
	MemoryUsage   int64 `json:"memory_usage"`    // memory usage (bytes)
	MemoryCache   int64 `json:"memory_cache"`    // memory cache (bytes)
	NetRxBytes    int64 `json:"net_rx_bytes"`    // network received bytes
	NetTxBytes    int64 `json:"net_tx_bytes"`    // network transmitted bytes
	NetRxPackets  int64 `json:"net_rx_packets"`  // network received packets
	NetTxPackets  int64 `json:"net_tx_packets"`  // network transmitted packets
	BlkReadBytes  int64 `json:"blk_read_bytes"`  // block device read bytes
	BlkWriteBytes int64 `json:"blk_write_bytes"` // block device write bytes
	BlkReadOps    int64 `json:"blk_read_ops"`    // block device read operations
	BlkWriteOps   int64 `json:"blk_write_ops"`   // block device write operations
}

// Driver defines the container runtime driver interface.
type Driver interface {
	Name() string

	Info(ctx context.Context) (*DriverInfo, error)
	Ping(ctx context.Context) error

	ContainerList(ctx context.Context) ([]*ContainerInfo, error)
	ContainerInspect(ctx context.Context, nameOrId string) (*ContainerInfo, error)
	ContainerCreate(ctx context.Context, opts *ContainerCreateOptions) (*ContainerInfo, error)
	ContainerStart(ctx context.Context, nameOrId string) error
	ContainerStop(ctx context.Context, nameOrId string) error
	ContainerRemove(ctx context.Context, nameOrId string) error
	// ContainerUpdateRestartPolicy changes a container's restart policy in
	// place (e.g. "no" to quarantine an orphan so a Docker daemon restart does
	// not resurrect it, "always" to restore normal lifecycle behavior).
	ContainerUpdateRestartPolicy(ctx context.Context, nameOrId, policy string) error
	// ContainerStats returns a snapshot of resource usage statistics for a
	// running container. Callers should skip non-running containers; the
	// returned values are cumulative counters where applicable.
	ContainerStats(ctx context.Context, nameOrId string) (*ContainerStats, error)

	ImageList(ctx context.Context) ([]*ImageInfo, error)
	ImagePull(ctx context.Context, image string) error
}
